// Code generated by protoc-gen-go. DO NOT EDIT.
// source: secretdgateway/secretdgateway.proto

package secretdgateway

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ForwardRequest struct {
	// A stateless secretd request message.
	RequestMessage       []byte   `protobuf:"bytes,1,opt,name=request_message,json=requestMessage,proto3" json:"request_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardRequest) Reset()         { *m = ForwardRequest{} }
func (m *ForwardRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardRequest) ProtoMessage()    {}
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89ab3c530df35f0a, []int{0}
}

func (m *ForwardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardRequest.Unmarshal(m, b)
}
func (m *ForwardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardRequest.Marshal(b, m, deterministic)
}
func (m *ForwardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardRequest.Merge(m, src)
}
func (m *ForwardRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardRequest.Size(m)
}
func (m *ForwardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardRequest proto.InternalMessageInfo

func (m *ForwardRequest) GetRequestMessage() []byte {
	if m != nil {
		return m.RequestMessage
	}
	return nil
}

type ForwardResponse struct {
	// A stateless secretd response message.
	ResponseMessage      []byte   `protobuf:"bytes,1,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardResponse) Reset()         { *m = ForwardResponse{} }
func (m *ForwardResponse) String() string { return proto.CompactTextString(m) }
func (*ForwardResponse) ProtoMessage()    {}
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89ab3c530df35f0a, []int{1}
}

func (m *ForwardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardResponse.Unmarshal(m, b)
}
func (m *ForwardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardResponse.Marshal(b, m, deterministic)
}
func (m *ForwardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardResponse.Merge(m, src)
}
func (m *ForwardResponse) XXX_Size() int {
	return xxx_messageInfo_ForwardResponse.Size(m)
}
func (m *ForwardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardResponse proto.InternalMessageInfo

func (m *ForwardResponse) GetResponseMessage() []byte {
	if m != nil {
		return m.ResponseMessage
	}
	return nil
}

type GetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89ab3c530df35f0a, []int{2}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

type Info struct {
	ClusterIdentity      string   `protobuf:"bytes,1,opt,name=cluster_identity,json=clusterIdentity,proto3" json:"cluster_identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_89ab3c530df35f0a, []int{3}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetClusterIdentity() string {
	if m != nil {
		return m.ClusterIdentity
	}
	return ""
}

func init() {
	proto.RegisterType((*ForwardRequest)(nil), "authcore.secretdgateway.v1.ForwardRequest")
	proto.RegisterType((*ForwardResponse)(nil), "authcore.secretdgateway.v1.ForwardResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "authcore.secretdgateway.v1.GetInfoRequest")
	proto.RegisterType((*Info)(nil), "authcore.secretdgateway.v1.Info")
}

func init() {
	proto.RegisterFile("secretdgateway/secretdgateway.proto", fileDescriptor_89ab3c530df35f0a)
}

var fileDescriptor_89ab3c530df35f0a = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xc5, 0x51, 0x21, 0x65, 0xa0, 0x71, 0x99, 0x6e, 0x90, 0xd5, 0xc5, 0xc8, 0x20, 0x15, 0x1a,
	0x62, 0xab, 0xb0, 0xe2, 0xb1, 0x31, 0x0b, 0xa2, 0x2e, 0xd8, 0x04, 0x56, 0xdd, 0x54, 0x93, 0xf1,
	0x8d, 0x33, 0x4a, 0x3a, 0x63, 0x66, 0xae, 0x1b, 0x99, 0x25, 0x5b, 0x76, 0xe1, 0x13, 0x58, 0xf0,
	0x17, 0x7c, 0x04, 0xfc, 0x02, 0x1f, 0x82, 0x6c, 0x8f, 0x23, 0xb9, 0x2f, 0x75, 0x95, 0xb9, 0xe7,
	0x9e, 0x73, 0xe7, 0x9e, 0x13, 0x0f, 0x79, 0x62, 0x41, 0x18, 0xc0, 0x34, 0xe3, 0x08, 0x2b, 0x5e,
	0xc6, 0xdd, 0x32, 0xca, 0x8d, 0x46, 0x4d, 0x03, 0x5e, 0xe0, 0x5c, 0x68, 0x03, 0xd1, 0x85, 0xf6,
	0xf9, 0x51, 0xb0, 0x9f, 0x69, 0x9d, 0x2d, 0x21, 0xe6, 0xb9, 0x8c, 0xb9, 0x52, 0x1a, 0x39, 0x4a,
	0xad, 0x6c, 0xa3, 0x0c, 0x5e, 0xd4, 0x3f, 0x62, 0x94, 0x81, 0x1a, 0xd9, 0x15, 0xcf, 0x32, 0x30,
	0xb1, 0xce, 0x6b, 0xc6, 0x65, 0x76, 0xf8, 0x9a, 0x0c, 0x3e, 0x68, 0xb3, 0xe2, 0x26, 0x9d, 0xc0,
	0x97, 0x02, 0x2c, 0xd2, 0x03, 0xe2, 0x9b, 0xe6, 0x78, 0x7a, 0x06, 0xd6, 0xf2, 0x0c, 0x1e, 0x7b,
	0xcc, 0x7b, 0xf6, 0x70, 0x32, 0x70, 0xf0, 0xc7, 0x06, 0x0d, 0xdf, 0x11, 0x7f, 0x23, 0xb5, 0xb9,
	0x56, 0x16, 0xe8, 0x73, 0xb2, 0x6b, 0xdc, 0xf9, 0x82, 0xd8, 0x6f, 0xf1, 0x56, 0xbd, 0x4b, 0x06,
	0x63, 0xc0, 0x63, 0x35, 0xd3, 0xee, 0xe2, 0xf0, 0x88, 0x6c, 0x55, 0x65, 0x35, 0x44, 0x2c, 0x0b,
	0x8b, 0x60, 0x4e, 0x65, 0x0a, 0x0a, 0x25, 0x96, 0xf5, 0x90, 0xfb, 0x13, 0xdf, 0xe1, 0xc7, 0x0e,
	0x7e, 0xf9, 0x7d, 0x8b, 0x0c, 0x3e, 0x35, 0xf9, 0x8c, 0x9b, 0x7c, 0xe8, 0xcf, 0x1e, 0xe9, 0xbb,
	0xb5, 0xe8, 0x61, 0x74, 0x7d, 0x8a, 0x51, 0xd7, 0x76, 0x30, 0xbc, 0x15, 0xb7, 0xf1, 0x10, 0xfe,
	0xf6, 0xd6, 0xc9, 0x2f, 0x8f, 0xee, 0x3b, 0x9c, 0x71, 0xe6, 0xb2, 0x61, 0xa8, 0x99, 0x93, 0x07,
	0xe8, 0xba, 0xf6, 0xca, 0x76, 0xc4, 0xdc, 0xe2, 0x2c, 0x95, 0x06, 0x04, 0x2e, 0x4b, 0x56, 0x2d,
	0x50, 0x19, 0x13, 0x1c, 0xc1, 0x32, 0x9c, 0xc3, 0x46, 0xc6, 0x55, 0x5a, 0xd7, 0x2e, 0x53, 0xcb,
	0xb8, 0x01, 0x06, 0x2a, 0x1d, 0xa1, 0x1e, 0x81, 0x4a, 0x19, 0x28, 0x61, 0xca, 0x1c, 0x21, 0x8d,
	0xa6, 0x8f, 0x88, 0x4f, 0x1e, 0x24, 0x42, 0x80, 0xb5, 0x9f, 0xf5, 0x02, 0x14, 0xbd, 0xf3, 0xed,
	0xef, 0xbf, 0x1f, 0xbd, 0x9d, 0x70, 0x3b, 0x9e, 0x35, 0xfb, 0xbc, 0xf1, 0x0e, 0xe9, 0x1f, 0x8f,
	0xf4, 0x5d, 0xfc, 0x37, 0xa7, 0xd4, 0xfd, 0x8f, 0x02, 0x76, 0x13, 0xb7, 0x22, 0x86, 0xe5, 0x3a,
	0x91, 0xf4, 0x60, 0x0c, 0xc8, 0xa4, 0x9a, 0x69, 0x73, 0x56, 0x7f, 0x6d, 0x8c, 0x4f, 0x75, 0x81,
	0x8c, 0xb7, 0xe6, 0x99, 0x05, 0x73, 0x2e, 0x05, 0x04, 0xc3, 0x09, 0x60, 0x61, 0x94, 0xbd, 0x0d,
	0xf9, 0x3a, 0x6b, 0x7d, 0x7a, 0x37, 0xae, 0xe4, 0xef, 0x17, 0xeb, 0xe4, 0x6d, 0xb8, 0x57, 0x3f,
	0x8b, 0xee, 0x72, 0x27, 0x4f, 0x49, 0xd8, 0x55, 0xee, 0x6d, 0xf7, 0x82, 0x9d, 0xa4, 0xc0, 0xb9,
	0x36, 0xf2, 0x6b, 0x73, 0x6b, 0xef, 0x64, 0xb8, 0xf1, 0x26, 0x75, 0xdc, 0x9e, 0xe3, 0x7c, 0x91,
	0x5d, 0x31, 0x72, 0x7a, 0xaf, 0x7e, 0x3f, 0xaf, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x41, 0x08,
	0x6a, 0x70, 0xce, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SecretdGatewayClient is the client API for SecretdGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecretdGatewayClient interface {
	// Forwards a request to secretd. Secretd will directly authenticates the request and the
	// messages are end-to-end encrypted.
	Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error)
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*Info, error)
}

type secretdGatewayClient struct {
	cc *grpc.ClientConn
}

func NewSecretdGatewayClient(cc *grpc.ClientConn) SecretdGatewayClient {
	return &secretdGatewayClient{cc}
}

func (c *secretdGatewayClient) Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error) {
	out := new(ForwardResponse)
	err := c.cc.Invoke(ctx, "/authcore.secretdgateway.v1.SecretdGateway/Forward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretdGatewayClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*Info, error) {
	out := new(Info)
	err := c.cc.Invoke(ctx, "/authcore.secretdgateway.v1.SecretdGateway/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretdGatewayServer is the server API for SecretdGateway service.
type SecretdGatewayServer interface {
	// Forwards a request to secretd. Secretd will directly authenticates the request and the
	// messages are end-to-end encrypted.
	Forward(context.Context, *ForwardRequest) (*ForwardResponse, error)
	GetInfo(context.Context, *GetInfoRequest) (*Info, error)
}

func RegisterSecretdGatewayServer(s *grpc.Server, srv SecretdGatewayServer) {
	s.RegisterService(&_SecretdGateway_serviceDesc, srv)
}

func _SecretdGateway_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretdGatewayServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authcore.secretdgateway.v1.SecretdGateway/Forward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretdGatewayServer).Forward(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretdGateway_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretdGatewayServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authcore.secretdgateway.v1.SecretdGateway/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretdGatewayServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecretdGateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authcore.secretdgateway.v1.SecretdGateway",
	HandlerType: (*SecretdGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forward",
			Handler:    _SecretdGateway_Forward_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _SecretdGateway_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secretdgateway/secretdgateway.proto",
}
