// INPUT_HANDLE_NOT_FOUND_ERROR represents the error case when the handle is not found
// in sign in case. The error in layout includes link to create account page which
// requires component interpolation.
export const INPUT_HANDLE_NOT_FOUND_ERROR = 'INPUT_HANDLE_NOT_FOUND_ERROR'

// INPUT_HANDLE_ALREADY_EXISTS_ERROR represents the error case when the handle is found
// in create account case. The error in layout includes link to sign in page which
// requires component interpolation.
export const INPUT_HANDLE_ALREADY_EXISTS_ERROR = 'INPUT_HANDLE_ALREADY_EXISTS_ERROR'

// client
export const GET_CLIENT_COMPLETED = 'GET_CLIENT_COMPLETED'
export const GET_CALLBACKS_COMPLETED = 'GET_CALLBACKS_COMPLETED'
export const GET_CONTAINER_PARAMETER_COMPLETED = 'GET_CONTAINER_PARAMETER_COMPLETED'
export const SET_LAYOUT_STATE = 'SET_LAYOUT_STATE'
export const SET_OAUTH_WIDGET_STATE = 'SET_OAUTH_WIDGET_STATE'
export const SET_AUTHENTICATED_STATE = 'SET_AUTHENTICATED_STATE'

// widgets
export const SET_DISPLAY_MODE_STATE = 'SET_DISPLAY_MODE_STATE'

// widgets/error_page
export const SET_ERROR = 'SET_ERROR'

// widgets/contacts_list
export const LIST_CONTACTS_STARTED = 'LIST_CONTACTS_STARTED'
export const LIST_CONTACTS_COMPLETED = 'LIST_CONTACTS_COMPLETED'
export const LIST_CONTACTS_FAILED = 'LIST_CONTACTS_FAILED'
export const RESEND_CONTACT_VERIFICATION_STARTED = 'RESEND_CONTACT_VERIFICATION_STARTED'
export const RESEND_CONTACT_VERIFICATION_COMPLETED = 'RESEND_CONTACT_VERIFICATION_COMPLETED'
export const RESEND_CONTACT_VERIFICATION_FAILED = 'RESEND_CONTACT_VERIFICATION_FAILED'
export const VERIFY_CONTACT_STARTED = 'VERIFY_CONTACT_STARTED'
export const VERIFY_CONTACT_COMPLETED = 'VERIFY_CONTACT_COMPLETED'
export const VERIFY_CONTACT_FAILED = 'VERIFY_CONTACT_FAILED'

// widgets/contacts_list/update_primary_contact_form
export const UPDATE_PRIMARY_CONTACT_SPINNER_STATE = 'UPDATE_PRIMARY_CONTACT_SPINNER_STATE'
export const UPDATE_PRIMARY_CONTACT_STARTED = 'UPDATE_PRIMARY_CONTACT_STARTED'
export const UPDATE_PRIMARY_CONTACT_COMPLETED = 'UPDATE_PRIMARY_CONTACT_COMPLETED'
export const UPDATE_PRIMARY_CONTACT_FAILED = 'UPDATE_PRIMARY_CONTACT_FAILED'

// widgets/contacts_list/create_contact_form
export const CREATE_CONTACT_SPINNER_STATE = 'CREATE_CONTACT_SPINNER_STATE'
export const CREATE_CONTACT_STARTED = 'CREATE_CONTACT_STARTED'
export const CREATE_CONTACT_COMPLETED = 'CREATE_CONTACT_COMPLETED'
export const CREATE_CONTACT_FAILED = 'CREATE_CONTACT_FAILED'

// widgets/contacts_list/delete_contact_form
export const DELETE_CONTACT_SPINNER_STATE = 'DELETE_CONTACT_SPINNER_STATE'
export const DELETE_CONTACT_STARTED = 'DELETE_CONTACT_STARTED'
export const DELETE_CONTACT_COMPLETED = 'DELETE_CONTACT_COMPLETED'
export const DELETE_CONTACT_FAILED = 'DELETE_CONTACT_FAILED'

// widgets/account
export const SET_PROFILE_COMPLETED = 'SET_PROFILE_COMPLETED'

export const GET_PROFILE_STARTED = 'GET_PROFILE_STARTED'
export const GET_PROFILE_COMPLETED = 'GET_PROFILE_COMPLETED'
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED'

export const UPDATE_PROFILE_SPINNER_STATE = 'UPDATE_PROFILE_SPINNER_STATE'
export const UPDATE_PROFILE_STARTED = 'UPDATE_PROFILE_STARTED'
export const UPDATE_PROFILE_COMPLETED = 'UPDATE_PROFILE_COMPLETED'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'

// widgets/account/login_account_form
export const AUTHENTICATE_HANDLE_STARTED = 'AUTHENTICATE_HANDLE_STARTED'
export const AUTHENTICATE_HANDLE_COMPLETED = 'AUTHENTICATE_HANDLE_COMPLETED'
export const AUTHENTICATE_HANDLE_FAILED = 'AUTHENTICATE_HANDLE_FAILED'

export const AUTHENTICATE_FACTOR_INIT = 'AUTHENTICATE_FACTOR_INIT'
export const AUTHENTICATE_FACTOR_SET = 'AUTHENTICATE_FACTOR_SET'
export const AUTHENTICATE_FACTOR_STARTED = 'AUTHENTICATE_FACTOR_STARTED'
export const AUTHENTICATE_FACTOR_COMPLETED = 'AUTHENTICATE_FACTOR_COMPLETED'
export const AUTHENTICATE_FACTOR_FAILED = 'AUTHENTICATE_FACTOR_FAILED'

export const PROVIDE_HEADER_ERROR_COMPLETED = 'PROVIDE_HEADER_ERROR_COMPLETED'
export const PROVIDE_CREATE_ACCOUNT_INFO_COMPLETED = 'PROVIDE_CREATE_ACCOUNT_INFO_COMPLETED'

export const CREATE_ACCESS_TOKEN_STARTED = 'CREATE_ACCESS_TOKEN_STARTED'
export const CREATE_ACCESS_TOKEN_COMPLETED = 'CREATE_ACCESS_TOKEN_COMPLETED'
export const CREATE_ACCESS_TOKEN_FAILED = 'CREATE_ACCESS_TOKEN_FAILED'

export const RESEND_SMS_AUTHENTICATION_CODE_INIT = 'RESEND_SMS_AUTHENTICATION_CODE_INIT'
export const RESEND_SMS_AUTHENTICATION_CODE_STARTED = 'RESEND_SMS_AUTHENTICATION_CODE_STARTED'
export const RESEND_SMS_AUTHENTICATION_CODE_COMPLETED = 'RESEND_SMS_AUTHENTICATION_CODE_COMPLETED'
export const RESEND_SMS_AUTHENTICATION_CODE_FAILED = 'RESEND_SMS_AUTHENTICATION_CODE_FAILED'

export const RESET_PASSWORD_STARTED = 'RESET_PASSWORD_STARTED'
export const RESET_PASSWORD_COMPLETED = 'RESET_PASSWORD_COMPLETED'
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'

export const SET_REDIRECT_URL = 'SET_REDIRECT_URL'

// widgets/account_register
export const REGISTER_ACCOUNT_SPINNER_STATE = 'REGISTER_ACCOUNT_SPINNER_STATE'
export const REGISTER_ACCOUNT_STARTED = 'REGISTER_ACCOUNT_STARTED'
export const REGISTER_ACCOUNT_COMPLETED = 'REGISTER_ACCOUNT_COMPLETED'
export const REGISTER_ACCOUNT_FAILED = 'REGISTER_ACCOUNT_FAILED'

export const UPDATE_FIELDS_COMPLETED = 'UPDATE_FIELDS_COMPLETED'
export const UPDATE_HIDDEN_FIELDS_COMPLETED = 'UPDATE_HIDDEN_FIELDS_COMPLETED'

// widgets/occount/verify_account_form
export const VERIFY_ACCOUNT_CONTACT_SPINNER_STATE = 'VERIFY_ACCOUNT_CONTACT_SPINNER_STATE'
export const VERIFY_ACCOUNT_CONTACT_RESET = 'VERIFY_ACCOUNT_CONTACT_RESET'
export const VERIFY_ACCOUNT_CONTACT_INIT = 'VERIFY_ACCOUNT_CONTACT_INIT'
export const VERIFY_ACCOUNT_CONTACT_STARTED = 'VERIFY_ACCOUNT_CONTACT_STARTED'
export const VERIFY_ACCOUNT_CONTACT_COMPLETED = 'VERIFY_ACCOUNT_CONTACT_COMPLETED'
export const VERIFY_ACCOUNT_CONTACT_FAILED = 'VERIFY_ACCOUNT_CONTACT_FAILED'

export const CREATE_AUTHORIZATION_TOKEN_COMPLETED = 'CREATE_AUTHORIZATION_TOKEN_COMPLETED'
export const CREATE_AUTHORIZATION_TOKEN_FAILED = 'CREATE_AUTHORIZATION_TOKEN_FAILED'

export const RESEND_VERIFY_ACCOUNT_CONTACT_INIT = 'RESEND_VERIFY_ACCOUNT_CONTACT_INIT'
export const RESEND_VERIFY_ACCOUNT_CONTACT_COMPLETED = 'RESEND_VERIFY_ACCOUNT_CONTACT_COMPLETED'

// widgets/external_oauth
export const OPEN_OAUTH_AUTHENTICATOR_STARTED = 'OPEN_OAUTH_AUTHENTICATOR_STARTED'
export const OPEN_OAUTH_AUTHENTICATOR_COMPLETED = 'OPEN_OAUTH_AUTHENTICATOR_COMPLETED'
export const OPEN_OAUTH_AUTHENTICATOR_FAILED = 'OPEN_OAUTH_AUTHENTICATOR_FAILED'

// *
export const CLEAR_STATES = 'CLEAR_STATES'
export const CLEAR_ACTION_STATES = 'CLEAR_ACTION_STATES'
