// Code generated by protoc-gen-go. DO NOT EDIT.
// source: managementapi/management_entity.proto

package managementapi

import (
	_ "authcore.io/authcore/pkg/api/authapi"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OAuthFactor_OAuthService int32

const (
	OAuthFactor_FACEBOOK OAuthFactor_OAuthService = 0
	OAuthFactor_GOOGLE   OAuthFactor_OAuthService = 1
	OAuthFactor_APPLE    OAuthFactor_OAuthService = 2
	OAuthFactor_MATTERS  OAuthFactor_OAuthService = 3
	OAuthFactor_TWITTER  OAuthFactor_OAuthService = 4
)

var OAuthFactor_OAuthService_name = map[int32]string{
	0: "FACEBOOK",
	1: "GOOGLE",
	2: "APPLE",
	3: "MATTERS",
	4: "TWITTER",
}

var OAuthFactor_OAuthService_value = map[string]int32{
	"FACEBOOK": 0,
	"GOOGLE":   1,
	"APPLE":    2,
	"MATTERS":  3,
	"TWITTER":  4,
}

func (x OAuthFactor_OAuthService) String() string {
	return proto.EnumName(OAuthFactor_OAuthService_name, int32(x))
}

func (OAuthFactor_OAuthService) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_035e44f418a3fed0, []int{2, 0}
}

type Role struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SystemRole           bool     `protobuf:"varint,3,opt,name=system_role,json=systemRole,proto3" json:"system_role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_035e44f418a3fed0, []int{0}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetSystemRole() bool {
	if m != nil {
		return m.SystemRole
	}
	return false
}

type Permission struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_035e44f418a3fed0, []int{1}
}

func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type OAuthFactor struct {
	Service              OAuthFactor_OAuthService `protobuf:"varint,1,opt,name=service,proto3,enum=authcore.managementapi.v1.OAuthFactor_OAuthService" json:"service,omitempty"`
	OauthUserId          string                   `protobuf:"bytes,2,opt,name=oauth_user_id,json=oauthUserId,proto3" json:"oauth_user_id,omitempty"`
	Metadata             string                   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OAuthFactor) Reset()         { *m = OAuthFactor{} }
func (m *OAuthFactor) String() string { return proto.CompactTextString(m) }
func (*OAuthFactor) ProtoMessage()    {}
func (*OAuthFactor) Descriptor() ([]byte, []int) {
	return fileDescriptor_035e44f418a3fed0, []int{2}
}

func (m *OAuthFactor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthFactor.Unmarshal(m, b)
}
func (m *OAuthFactor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthFactor.Marshal(b, m, deterministic)
}
func (m *OAuthFactor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthFactor.Merge(m, src)
}
func (m *OAuthFactor) XXX_Size() int {
	return xxx_messageInfo_OAuthFactor.Size(m)
}
func (m *OAuthFactor) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthFactor.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthFactor proto.InternalMessageInfo

func (m *OAuthFactor) GetService() OAuthFactor_OAuthService {
	if m != nil {
		return m.Service
	}
	return OAuthFactor_FACEBOOK
}

func (m *OAuthFactor) GetOauthUserId() string {
	if m != nil {
		return m.OauthUserId
	}
	return ""
}

func (m *OAuthFactor) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type Template struct {
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Template:
	//	*Template_EmailTemplate
	//	*Template_SmsTemplate
	Template             isTemplate_Template  `protobuf_oneof:"template"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_035e44f418a3fed0, []int{3}
}

func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (m *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(m, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Template) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isTemplate_Template interface {
	isTemplate_Template()
}

type Template_EmailTemplate struct {
	EmailTemplate *EmailTemplate `protobuf:"bytes,3,opt,name=email_template,json=emailTemplate,proto3,oneof"`
}

type Template_SmsTemplate struct {
	SmsTemplate *SMSTemplate `protobuf:"bytes,4,opt,name=sms_template,json=smsTemplate,proto3,oneof"`
}

func (*Template_EmailTemplate) isTemplate_Template() {}

func (*Template_SmsTemplate) isTemplate_Template() {}

func (m *Template) GetTemplate() isTemplate_Template {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *Template) GetEmailTemplate() *EmailTemplate {
	if x, ok := m.GetTemplate().(*Template_EmailTemplate); ok {
		return x.EmailTemplate
	}
	return nil
}

func (m *Template) GetSmsTemplate() *SMSTemplate {
	if x, ok := m.GetTemplate().(*Template_SmsTemplate); ok {
		return x.SmsTemplate
	}
	return nil
}

func (m *Template) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Template) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Template_EmailTemplate)(nil),
		(*Template_SmsTemplate)(nil),
	}
}

type EmailTemplate struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	HtmlTemplate         string   `protobuf:"bytes,2,opt,name=html_template,json=htmlTemplate,proto3" json:"html_template,omitempty"`
	TextTemplate         string   `protobuf:"bytes,3,opt,name=text_template,json=textTemplate,proto3" json:"text_template,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailTemplate) Reset()         { *m = EmailTemplate{} }
func (m *EmailTemplate) String() string { return proto.CompactTextString(m) }
func (*EmailTemplate) ProtoMessage()    {}
func (*EmailTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_035e44f418a3fed0, []int{4}
}

func (m *EmailTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailTemplate.Unmarshal(m, b)
}
func (m *EmailTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailTemplate.Marshal(b, m, deterministic)
}
func (m *EmailTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailTemplate.Merge(m, src)
}
func (m *EmailTemplate) XXX_Size() int {
	return xxx_messageInfo_EmailTemplate.Size(m)
}
func (m *EmailTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_EmailTemplate proto.InternalMessageInfo

func (m *EmailTemplate) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailTemplate) GetHtmlTemplate() string {
	if m != nil {
		return m.HtmlTemplate
	}
	return ""
}

func (m *EmailTemplate) GetTextTemplate() string {
	if m != nil {
		return m.TextTemplate
	}
	return ""
}

type SMSTemplate struct {
	Template             string   `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSTemplate) Reset()         { *m = SMSTemplate{} }
func (m *SMSTemplate) String() string { return proto.CompactTextString(m) }
func (*SMSTemplate) ProtoMessage()    {}
func (*SMSTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_035e44f418a3fed0, []int{5}
}

func (m *SMSTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSTemplate.Unmarshal(m, b)
}
func (m *SMSTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSTemplate.Marshal(b, m, deterministic)
}
func (m *SMSTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSTemplate.Merge(m, src)
}
func (m *SMSTemplate) XXX_Size() int {
	return xxx_messageInfo_SMSTemplate.Size(m)
}
func (m *SMSTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_SMSTemplate proto.InternalMessageInfo

func (m *SMSTemplate) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

type TemplateLanguage struct {
	Language             string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateLanguage) Reset()         { *m = TemplateLanguage{} }
func (m *TemplateLanguage) String() string { return proto.CompactTextString(m) }
func (*TemplateLanguage) ProtoMessage()    {}
func (*TemplateLanguage) Descriptor() ([]byte, []int) {
	return fileDescriptor_035e44f418a3fed0, []int{6}
}

func (m *TemplateLanguage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateLanguage.Unmarshal(m, b)
}
func (m *TemplateLanguage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateLanguage.Marshal(b, m, deterministic)
}
func (m *TemplateLanguage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateLanguage.Merge(m, src)
}
func (m *TemplateLanguage) XXX_Size() int {
	return xxx_messageInfo_TemplateLanguage.Size(m)
}
func (m *TemplateLanguage) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateLanguage.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateLanguage proto.InternalMessageInfo

func (m *TemplateLanguage) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func init() {
	proto.RegisterEnum("authcore.managementapi.v1.OAuthFactor_OAuthService", OAuthFactor_OAuthService_name, OAuthFactor_OAuthService_value)
	proto.RegisterType((*Role)(nil), "authcore.managementapi.v1.Role")
	proto.RegisterType((*Permission)(nil), "authcore.managementapi.v1.Permission")
	proto.RegisterType((*OAuthFactor)(nil), "authcore.managementapi.v1.OAuthFactor")
	proto.RegisterType((*Template)(nil), "authcore.managementapi.v1.Template")
	proto.RegisterType((*EmailTemplate)(nil), "authcore.managementapi.v1.EmailTemplate")
	proto.RegisterType((*SMSTemplate)(nil), "authcore.managementapi.v1.SMSTemplate")
	proto.RegisterType((*TemplateLanguage)(nil), "authcore.managementapi.v1.TemplateLanguage")
}

func init() {
	proto.RegisterFile("managementapi/management_entity.proto", fileDescriptor_035e44f418a3fed0)
}

var fileDescriptor_035e44f418a3fed0 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xd1, 0x6e, 0xda, 0x30,
	0x14, 0x86, 0x1b, 0x4a, 0x5b, 0x38, 0x01, 0x14, 0xf9, 0x8a, 0x21, 0x4d, 0x45, 0xa9, 0x36, 0xb1,
	0x69, 0x0a, 0x5a, 0x7b, 0xb5, 0x4b, 0x98, 0x68, 0x57, 0x01, 0x82, 0x05, 0xa6, 0x49, 0xbb, 0x89,
	0x0c, 0x39, 0x0b, 0xde, 0xe2, 0x24, 0x8a, 0x9d, 0x6a, 0x7d, 0x9c, 0x3d, 0xdf, 0x5e, 0x62, 0x72,
	0x82, 0x43, 0x90, 0x36, 0xee, 0x72, 0x8e, 0xfe, 0xff, 0xcb, 0xf1, 0x7f, 0x6c, 0x78, 0xc5, 0x69,
	0x44, 0x03, 0xe4, 0x18, 0x49, 0x9a, 0xb0, 0xe1, 0xa1, 0xf2, 0x30, 0x92, 0x4c, 0x3e, 0x3b, 0x49,
	0x1a, 0xcb, 0x98, 0xbc, 0xa0, 0x99, 0xdc, 0x6d, 0xe3, 0x14, 0x9d, 0x23, 0xbd, 0xf3, 0xf4, 0xbe,
	0x77, 0x1d, 0xc4, 0x71, 0x10, 0xe2, 0x30, 0x17, 0x6e, 0xb2, 0xef, 0x43, 0xc9, 0x38, 0x0a, 0x49,
	0x79, 0x52, 0x78, 0x7b, 0x2f, 0x95, 0x57, 0xc1, 0x35, 0xe3, 0x08, 0x6d, 0x4f, 0xa1, 0xee, 0xc6,
	0x21, 0x92, 0x0e, 0xd4, 0x98, 0xdf, 0x35, 0xfa, 0xc6, 0xe0, 0xdc, 0xad, 0x31, 0x9f, 0x10, 0xa8,
	0x47, 0x94, 0x63, 0xb7, 0xd6, 0x37, 0x06, 0x4d, 0x37, 0xff, 0x26, 0xd7, 0x60, 0x8a, 0x67, 0x21,
	0x91, 0x7b, 0x69, 0x1c, 0x62, 0xf7, 0xbc, 0x6f, 0x0c, 0x1a, 0x2e, 0x14, 0x2d, 0x05, 0xb1, 0xfb,
	0x00, 0x4b, 0x4c, 0x39, 0x13, 0x82, 0xc5, 0x51, 0x89, 0x30, 0x0e, 0x08, 0xfb, 0x8f, 0x01, 0xe6,
	0x62, 0x94, 0xc9, 0xdd, 0x3d, 0xdd, 0xca, 0x38, 0x25, 0x73, 0xb8, 0x12, 0x98, 0x3e, 0xb1, 0x6d,
	0x21, 0xeb, 0xdc, 0xde, 0x39, 0xff, 0x3d, 0xab, 0x53, 0x31, 0x16, 0xdf, 0xab, 0xc2, 0xea, 0x6a,
	0x06, 0xb1, 0xa1, 0x1d, 0x2b, 0xbf, 0x97, 0x09, 0x4c, 0x3d, 0xe6, 0xef, 0xc7, 0x37, 0xf3, 0xe6,
	0x17, 0x81, 0xe9, 0xa3, 0x4f, 0x7a, 0xd0, 0xe0, 0x28, 0xa9, 0x4f, 0x25, 0xcd, 0x8f, 0xd0, 0x74,
	0xcb, 0xda, 0x9e, 0x43, 0xab, 0x0a, 0x26, 0x2d, 0x68, 0xdc, 0x8f, 0x3e, 0x4e, 0xc6, 0x8b, 0xc5,
	0xd4, 0x3a, 0x23, 0x00, 0x97, 0x0f, 0x8b, 0xc5, 0xc3, 0x6c, 0x62, 0x19, 0xa4, 0x09, 0x17, 0xa3,
	0xe5, 0x72, 0x36, 0xb1, 0x6a, 0xc4, 0x84, 0xab, 0xf9, 0x68, 0xbd, 0x9e, 0xb8, 0x2b, 0xeb, 0x5c,
	0x15, 0xeb, 0xaf, 0x8f, 0xaa, 0xb2, 0xea, 0xf6, 0xef, 0x1a, 0x34, 0xd6, 0xc8, 0x93, 0x90, 0x4a,
	0x54, 0xff, 0x0d, 0x69, 0x14, 0x64, 0x34, 0xd0, 0x91, 0x94, 0xf5, 0x3f, 0xd3, 0xfe, 0x0c, 0x1d,
	0xe4, 0x94, 0x85, 0x9e, 0xdc, 0x13, 0xf2, 0x69, 0xcd, 0xdb, 0xc1, 0x89, 0x84, 0x26, 0xca, 0xa0,
	0xff, 0xf8, 0xe9, 0xcc, 0x6d, 0x63, 0xb5, 0x41, 0xa6, 0xd0, 0x12, 0x5c, 0x1c, 0x80, 0xf5, 0x1c,
	0xf8, 0xfa, 0x04, 0x70, 0x35, 0x5f, 0x55, 0x70, 0xa6, 0xe0, 0xa2, 0x84, 0x7d, 0x00, 0xc8, 0x12,
	0x9f, 0x4a, 0xf4, 0x3d, 0x2a, 0xbb, 0x17, 0x39, 0xaa, 0xe7, 0x14, 0xd7, 0xd1, 0xd1, 0xd7, 0xd1,
	0x59, 0xeb, 0xeb, 0xe8, 0x36, 0xf7, 0xea, 0x91, 0x1c, 0x03, 0x34, 0xf4, 0x0c, 0xb6, 0x80, 0xf6,
	0xd1, 0xd4, 0xa4, 0x0b, 0x57, 0x22, 0xdb, 0xfc, 0xc0, 0xad, 0xdc, 0xc7, 0xa4, 0x4b, 0x72, 0x03,
	0xed, 0x9d, 0xe4, 0x95, 0x40, 0x8a, 0xb8, 0x5a, 0xaa, 0x59, 0xda, 0x6f, 0xa0, 0x2d, 0xf1, 0x97,
	0x3c, 0x4e, 0xad, 0xe9, 0xb6, 0x54, 0x53, 0x8b, 0xec, 0x37, 0x60, 0x56, 0x4e, 0xa6, 0x56, 0x53,
	0xca, 0xf7, 0xab, 0x29, 0xe7, 0x73, 0xc0, 0xd2, 0xba, 0x99, 0x5e, 0xd7, 0x89, 0x55, 0x8e, 0xdf,
	0x7d, 0x7b, 0x5b, 0xc6, 0xc9, 0xe2, 0xf2, 0xd5, 0x0d, 0x93, 0x9f, 0xc1, 0xf0, 0xf8, 0x8d, 0xd3,
	0x84, 0x6d, 0x2e, 0xf3, 0xa0, 0xee, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x77, 0xb4, 0x2b, 0xef,
	0x09, 0x04, 0x00, 0x00,
}
