// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authapi/authcore_entity.proto

package authapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthenticationState_ChallengeType int32

const (
	AuthenticationState_PASSWORD                     AuthenticationState_ChallengeType = 0
	AuthenticationState_TIME_BASED_ONE_TIME_PASSWORD AuthenticationState_ChallengeType = 1
	AuthenticationState_UNIVERSAL_TWO_FACTOR         AuthenticationState_ChallengeType = 2
	AuthenticationState_EMAIL_CODE                   AuthenticationState_ChallengeType = 3
	AuthenticationState_SMS_CODE                     AuthenticationState_ChallengeType = 4
	AuthenticationState_OAUTH                        AuthenticationState_ChallengeType = 5
	AuthenticationState_BACKUP_CODE                  AuthenticationState_ChallengeType = 6
)

var AuthenticationState_ChallengeType_name = map[int32]string{
	0: "PASSWORD",
	1: "TIME_BASED_ONE_TIME_PASSWORD",
	2: "UNIVERSAL_TWO_FACTOR",
	3: "EMAIL_CODE",
	4: "SMS_CODE",
	5: "OAUTH",
	6: "BACKUP_CODE",
}

var AuthenticationState_ChallengeType_value = map[string]int32{
	"PASSWORD":                     0,
	"TIME_BASED_ONE_TIME_PASSWORD": 1,
	"UNIVERSAL_TWO_FACTOR":         2,
	"EMAIL_CODE":                   3,
	"SMS_CODE":                     4,
	"OAUTH":                        5,
	"BACKUP_CODE":                  6,
}

func (x AuthenticationState_ChallengeType) String() string {
	return proto.EnumName(AuthenticationState_ChallengeType_name, int32(x))
}

func (AuthenticationState_ChallengeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{0, 0}
}

type ResetPasswordAuthenticationState_ChallengeType int32

const (
	ResetPasswordAuthenticationState_CONTACT_TOKEN ResetPasswordAuthenticationState_ChallengeType = 0
)

var ResetPasswordAuthenticationState_ChallengeType_name = map[int32]string{
	0: "CONTACT_TOKEN",
}

var ResetPasswordAuthenticationState_ChallengeType_value = map[string]int32{
	"CONTACT_TOKEN": 0,
}

func (x ResetPasswordAuthenticationState_ChallengeType) String() string {
	return proto.EnumName(ResetPasswordAuthenticationState_ChallengeType_name, int32(x))
}

func (ResetPasswordAuthenticationState_ChallengeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{1, 0}
}

type Contact_Type int32

const (
	Contact_EMAIL Contact_Type = 0
	Contact_PHONE Contact_Type = 1
)

var Contact_Type_name = map[int32]string{
	0: "EMAIL",
	1: "PHONE",
}

var Contact_Type_value = map[string]int32{
	"EMAIL": 0,
	"PHONE": 1,
}

func (x Contact_Type) String() string {
	return proto.EnumName(Contact_Type_name, int32(x))
}

func (Contact_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{3, 0}
}

type AuditLogEntity_Result int32

const (
	AuditLogEntity_UNKNOWN AuditLogEntity_Result = 0
	AuditLogEntity_FAIL    AuditLogEntity_Result = 1
	AuditLogEntity_SUCCESS AuditLogEntity_Result = 2
)

var AuditLogEntity_Result_name = map[int32]string{
	0: "UNKNOWN",
	1: "FAIL",
	2: "SUCCESS",
}

var AuditLogEntity_Result_value = map[string]int32{
	"UNKNOWN": 0,
	"FAIL":    1,
	"SUCCESS": 2,
}

func (x AuditLogEntity_Result) String() string {
	return proto.EnumName(AuditLogEntity_Result_name, int32(x))
}

func (AuditLogEntity_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{5, 0}
}

type AccessToken_TokenType int32

const (
	AccessToken_BEARER AccessToken_TokenType = 0
)

var AccessToken_TokenType_name = map[int32]string{
	0: "BEARER",
}

var AccessToken_TokenType_value = map[string]int32{
	"BEARER": 0,
}

func (x AccessToken_TokenType) String() string {
	return proto.EnumName(AccessToken_TokenType_name, int32(x))
}

func (AccessToken_TokenType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{7, 0}
}

type TOTPAuthenticator_Status int32

const (
	TOTPAuthenticator_ACTIVE   TOTPAuthenticator_Status = 0
	TOTPAuthenticator_INACTIVE TOTPAuthenticator_Status = 1
)

var TOTPAuthenticator_Status_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
}

var TOTPAuthenticator_Status_value = map[string]int32{
	"ACTIVE":   0,
	"INACTIVE": 1,
}

func (x TOTPAuthenticator_Status) String() string {
	return proto.EnumName(TOTPAuthenticator_Status_name, int32(x))
}

func (TOTPAuthenticator_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{19, 0}
}

type OAuthFactor_OAuthService int32

const (
	OAuthFactor_FACEBOOK OAuthFactor_OAuthService = 0
	OAuthFactor_GOOGLE   OAuthFactor_OAuthService = 1
	OAuthFactor_APPLE    OAuthFactor_OAuthService = 2
	OAuthFactor_MATTERS  OAuthFactor_OAuthService = 3
	OAuthFactor_TWITTER  OAuthFactor_OAuthService = 4
)

var OAuthFactor_OAuthService_name = map[int32]string{
	0: "FACEBOOK",
	1: "GOOGLE",
	2: "APPLE",
	3: "MATTERS",
	4: "TWITTER",
}

var OAuthFactor_OAuthService_value = map[string]int32{
	"FACEBOOK": 0,
	"GOOGLE":   1,
	"APPLE":    2,
	"MATTERS":  3,
	"TWITTER":  4,
}

func (x OAuthFactor_OAuthService) String() string {
	return proto.EnumName(OAuthFactor_OAuthService_name, int32(x))
}

func (OAuthFactor_OAuthService) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{20, 0}
}

type SecondFactor_Type int32

const (
	SecondFactor_SMS         SecondFactor_Type = 0
	SecondFactor_TOTP        SecondFactor_Type = 1
	SecondFactor_BACKUP_CODE SecondFactor_Type = 2
)

var SecondFactor_Type_name = map[int32]string{
	0: "SMS",
	1: "TOTP",
	2: "BACKUP_CODE",
}

var SecondFactor_Type_value = map[string]int32{
	"SMS":         0,
	"TOTP":        1,
	"BACKUP_CODE": 2,
}

func (x SecondFactor_Type) String() string {
	return proto.EnumName(SecondFactor_Type_name, int32(x))
}

func (SecondFactor_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{21, 0}
}

type AuthenticationState struct {
	// The temporary token to identify the authentication request.
	TemporaryToken string `protobuf:"bytes,1,opt,name=temporary_token,json=temporaryToken,proto3" json:"temporary_token,omitempty"`
	// A boolean that indicates whether session is authenticated.
	Authenticated bool `protobuf:"varint,2,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	// The ID of the authenticated user, or an empty string if the session is not authenticated.
	AuthenticatedUserId string `protobuf:"bytes,3,opt,name=authenticated_user_id,json=authenticatedUserId,proto3" json:"authenticated_user_id,omitempty"`
	// A list of ChallengeType that the client can attempt to complete authenticating as a user.
	Challenges []AuthenticationState_ChallengeType `protobuf:"varint,4,rep,packed,name=challenges,proto3,enum=authcore.authapi.v1.AuthenticationState_ChallengeType" json:"challenges,omitempty"`
	// A new PasswordChallenge if PASSWORD is one of the `challenges`. Otherwise, it
	// will be empty.
	PasswordChallenge *PasswordChallenge `protobuf:"bytes,5,opt,name=password_challenge,json=passwordChallenge,proto3" json:"password_challenge,omitempty"`
	PasswordSalt      []byte             `protobuf:"bytes,7,opt,name=password_salt,json=passwordSalt,proto3" json:"password_salt,omitempty"`
	// The authorization token for the user, or an empty string if the session is not authenticated.
	AuthorizationToken string `protobuf:"bytes,6,opt,name=authorization_token,json=authorizationToken,proto3" json:"authorization_token,omitempty"`
	// The URL that the widget should redirect to. Should not redirect if this field is left blank.
	RedirectUrl          string   `protobuf:"bytes,8,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationState) Reset()         { *m = AuthenticationState{} }
func (m *AuthenticationState) String() string { return proto.CompactTextString(m) }
func (*AuthenticationState) ProtoMessage()    {}
func (*AuthenticationState) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{0}
}

func (m *AuthenticationState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationState.Unmarshal(m, b)
}
func (m *AuthenticationState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationState.Marshal(b, m, deterministic)
}
func (m *AuthenticationState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationState.Merge(m, src)
}
func (m *AuthenticationState) XXX_Size() int {
	return xxx_messageInfo_AuthenticationState.Size(m)
}
func (m *AuthenticationState) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationState.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationState proto.InternalMessageInfo

func (m *AuthenticationState) GetTemporaryToken() string {
	if m != nil {
		return m.TemporaryToken
	}
	return ""
}

func (m *AuthenticationState) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func (m *AuthenticationState) GetAuthenticatedUserId() string {
	if m != nil {
		return m.AuthenticatedUserId
	}
	return ""
}

func (m *AuthenticationState) GetChallenges() []AuthenticationState_ChallengeType {
	if m != nil {
		return m.Challenges
	}
	return nil
}

func (m *AuthenticationState) GetPasswordChallenge() *PasswordChallenge {
	if m != nil {
		return m.PasswordChallenge
	}
	return nil
}

func (m *AuthenticationState) GetPasswordSalt() []byte {
	if m != nil {
		return m.PasswordSalt
	}
	return nil
}

func (m *AuthenticationState) GetAuthorizationToken() string {
	if m != nil {
		return m.AuthorizationToken
	}
	return ""
}

func (m *AuthenticationState) GetRedirectUrl() string {
	if m != nil {
		return m.RedirectUrl
	}
	return ""
}

type ResetPasswordAuthenticationState struct {
	// The temporary token to identify the authentication request.
	TemporaryToken string `protobuf:"bytes,1,opt,name=temporary_token,json=temporaryToken,proto3" json:"temporary_token,omitempty"`
	// A boolean that indicates whether session is authenticated.
	Authenticated bool `protobuf:"varint,2,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	// The ID of the authenticated user, or an empty string if the session is not authenticated.
	ResetPasswordUserId string `protobuf:"bytes,3,opt,name=reset_password_user_id,json=resetPasswordUserId,proto3" json:"reset_password_user_id,omitempty"`
	// A list of ChallengeType that the client can attempt to complete authenticating as a user.
	Challenges []ResetPasswordAuthenticationState_ChallengeType `protobuf:"varint,4,rep,packed,name=challenges,proto3,enum=authcore.authapi.v1.ResetPasswordAuthenticationState_ChallengeType" json:"challenges,omitempty"`
	// The reset password token for the user, or an empty string if the session is not authenticated.
	ResetPasswordToken   string   `protobuf:"bytes,5,opt,name=reset_password_token,json=resetPasswordToken,proto3" json:"reset_password_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordAuthenticationState) Reset()         { *m = ResetPasswordAuthenticationState{} }
func (m *ResetPasswordAuthenticationState) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordAuthenticationState) ProtoMessage()    {}
func (*ResetPasswordAuthenticationState) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{1}
}

func (m *ResetPasswordAuthenticationState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordAuthenticationState.Unmarshal(m, b)
}
func (m *ResetPasswordAuthenticationState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordAuthenticationState.Marshal(b, m, deterministic)
}
func (m *ResetPasswordAuthenticationState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordAuthenticationState.Merge(m, src)
}
func (m *ResetPasswordAuthenticationState) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordAuthenticationState.Size(m)
}
func (m *ResetPasswordAuthenticationState) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordAuthenticationState.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordAuthenticationState proto.InternalMessageInfo

func (m *ResetPasswordAuthenticationState) GetTemporaryToken() string {
	if m != nil {
		return m.TemporaryToken
	}
	return ""
}

func (m *ResetPasswordAuthenticationState) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func (m *ResetPasswordAuthenticationState) GetResetPasswordUserId() string {
	if m != nil {
		return m.ResetPasswordUserId
	}
	return ""
}

func (m *ResetPasswordAuthenticationState) GetChallenges() []ResetPasswordAuthenticationState_ChallengeType {
	if m != nil {
		return m.Challenges
	}
	return nil
}

func (m *ResetPasswordAuthenticationState) GetResetPasswordToken() string {
	if m != nil {
		return m.ResetPasswordToken
	}
	return ""
}

type User struct {
	Id                     string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username               string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PrimaryEmail           string               `protobuf:"bytes,3,opt,name=primary_email,json=primaryEmail,proto3" json:"primary_email,omitempty"`
	PrimaryEmailVerified   *timestamp.Timestamp `protobuf:"bytes,14,opt,name=primary_email_verified,json=primaryEmailVerified,proto3" json:"primary_email_verified,omitempty"`
	PrimaryPhone           string               `protobuf:"bytes,4,opt,name=primary_phone,json=primaryPhone,proto3" json:"primary_phone,omitempty"`
	PrimaryPhoneVerified   *timestamp.Timestamp `protobuf:"bytes,15,opt,name=primary_phone_verified,json=primaryPhoneVerified,proto3" json:"primary_phone_verified,omitempty"`
	RecoveryEmail          string               `protobuf:"bytes,18,opt,name=recovery_email,json=recoveryEmail,proto3" json:"recovery_email,omitempty"`
	RecoveryEmailVerified  *timestamp.Timestamp `protobuf:"bytes,19,opt,name=recovery_email_verified,json=recoveryEmailVerified,proto3" json:"recovery_email_verified,omitempty"`
	DisplayName            string               `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	UserInfo               string               `protobuf:"bytes,6,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	LastSeenAt             *timestamp.Timestamp `protobuf:"bytes,20,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	UpdatedAt              *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt              *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Contacts               []*Contact           `protobuf:"bytes,9,rep,name=contacts,proto3" json:"contacts,omitempty"`
	SmsAuthentication      bool                 `protobuf:"varint,10,opt,name=sms_authentication,json=smsAuthentication,proto3" json:"sms_authentication,omitempty"`
	Locked                 bool                 `protobuf:"varint,11,opt,name=locked,proto3" json:"locked,omitempty"`
	LockExpiredAt          *timestamp.Timestamp `protobuf:"bytes,12,opt,name=lock_expired_at,json=lockExpiredAt,proto3" json:"lock_expired_at,omitempty"`
	LockDescription        string               `protobuf:"bytes,13,opt,name=lock_description,json=lockDescription,proto3" json:"lock_description,omitempty"`
	TotpAuthentication     bool                 `protobuf:"varint,16,opt,name=totp_authentication,json=totpAuthentication,proto3" json:"totp_authentication,omitempty"`
	PasswordAuthentication bool                 `protobuf:"varint,17,opt,name=password_authentication,json=passwordAuthentication,proto3" json:"password_authentication,omitempty"`
	Language               string               `protobuf:"bytes,21,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}             `json:"-"`
	XXX_unrecognized       []byte               `json:"-"`
	XXX_sizecache          int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPrimaryEmail() string {
	if m != nil {
		return m.PrimaryEmail
	}
	return ""
}

func (m *User) GetPrimaryEmailVerified() *timestamp.Timestamp {
	if m != nil {
		return m.PrimaryEmailVerified
	}
	return nil
}

func (m *User) GetPrimaryPhone() string {
	if m != nil {
		return m.PrimaryPhone
	}
	return ""
}

func (m *User) GetPrimaryPhoneVerified() *timestamp.Timestamp {
	if m != nil {
		return m.PrimaryPhoneVerified
	}
	return nil
}

func (m *User) GetRecoveryEmail() string {
	if m != nil {
		return m.RecoveryEmail
	}
	return ""
}

func (m *User) GetRecoveryEmailVerified() *timestamp.Timestamp {
	if m != nil {
		return m.RecoveryEmailVerified
	}
	return nil
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetUserInfo() string {
	if m != nil {
		return m.UserInfo
	}
	return ""
}

func (m *User) GetLastSeenAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastSeenAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *User) GetSmsAuthentication() bool {
	if m != nil {
		return m.SmsAuthentication
	}
	return false
}

func (m *User) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

func (m *User) GetLockExpiredAt() *timestamp.Timestamp {
	if m != nil {
		return m.LockExpiredAt
	}
	return nil
}

func (m *User) GetLockDescription() string {
	if m != nil {
		return m.LockDescription
	}
	return ""
}

func (m *User) GetTotpAuthentication() bool {
	if m != nil {
		return m.TotpAuthentication
	}
	return false
}

func (m *User) GetPasswordAuthentication() bool {
	if m != nil {
		return m.PasswordAuthentication
	}
	return false
}

func (m *User) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

// An email or phone number registered by a user.
type Contact struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 Contact_Type `protobuf:"varint,2,opt,name=type,proto3,enum=authcore.authapi.v1.Contact_Type" json:"type,omitempty"`
	Value                string       `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Verified             bool         `protobuf:"varint,4,opt,name=verified,proto3" json:"verified,omitempty"`
	Primary              bool         `protobuf:"varint,5,opt,name=primary,proto3" json:"primary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{3}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contact) GetType() Contact_Type {
	if m != nil {
		return m.Type
	}
	return Contact_EMAIL
}

func (m *Contact) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Contact) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *Contact) GetPrimary() bool {
	if m != nil {
		return m.Primary
	}
	return false
}

// An active session.
type Session struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             string               `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LastSeenIp           string               `protobuf:"bytes,4,opt,name=last_seen_ip,json=lastSeenIp,proto3" json:"last_seen_ip,omitempty"`
	LastSeenAt           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	LastSeenLocation     string               `protobuf:"bytes,6,opt,name=last_seen_location,json=lastSeenLocation,proto3" json:"last_seen_location,omitempty"`
	UserAgent            string               `protobuf:"bytes,7,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ExpiredAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsCurrent            bool                 `protobuf:"varint,10,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{4}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Session) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Session) GetLastSeenIp() string {
	if m != nil {
		return m.LastSeenIp
	}
	return ""
}

func (m *Session) GetLastSeenAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastSeenAt
	}
	return nil
}

func (m *Session) GetLastSeenLocation() string {
	if m != nil {
		return m.LastSeenLocation
	}
	return ""
}

func (m *Session) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *Session) GetExpiredAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiredAt
	}
	return nil
}

func (m *Session) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Session) GetIsCurrent() bool {
	if m != nil {
		return m.IsCurrent
	}
	return false
}

// An audit log entry.
type AuditLogEntity struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string                `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Action               string                `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Target               *_struct.Struct       `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	SessionId            string                `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Device               string                `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	Ip                   string                `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	Description          string                `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Result               AuditLogEntity_Result `protobuf:"varint,9,opt,name=result,proto3,enum=authcore.authapi.v1.AuditLogEntity_Result" json:"result,omitempty"`
	IsExternal           bool                  `protobuf:"varint,10,opt,name=is_external,json=isExternal,proto3" json:"is_external,omitempty"`
	CreatedAt            *timestamp.Timestamp  `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AuditLogEntity) Reset()         { *m = AuditLogEntity{} }
func (m *AuditLogEntity) String() string { return proto.CompactTextString(m) }
func (*AuditLogEntity) ProtoMessage()    {}
func (*AuditLogEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{5}
}

func (m *AuditLogEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditLogEntity.Unmarshal(m, b)
}
func (m *AuditLogEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditLogEntity.Marshal(b, m, deterministic)
}
func (m *AuditLogEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditLogEntity.Merge(m, src)
}
func (m *AuditLogEntity) XXX_Size() int {
	return xxx_messageInfo_AuditLogEntity.Size(m)
}
func (m *AuditLogEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditLogEntity.DiscardUnknown(m)
}

var xxx_messageInfo_AuditLogEntity proto.InternalMessageInfo

func (m *AuditLogEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuditLogEntity) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuditLogEntity) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *AuditLogEntity) GetTarget() *_struct.Struct {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *AuditLogEntity) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *AuditLogEntity) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *AuditLogEntity) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AuditLogEntity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AuditLogEntity) GetResult() AuditLogEntity_Result {
	if m != nil {
		return m.Result
	}
	return AuditLogEntity_UNKNOWN
}

func (m *AuditLogEntity) GetIsExternal() bool {
	if m != nil {
		return m.IsExternal
	}
	return false
}

func (m *AuditLogEntity) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type AuthorizationToken struct {
	AuthorizationToken   string   `protobuf:"bytes,1,opt,name=authorization_token,json=authorizationToken,proto3" json:"authorization_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationToken) Reset()         { *m = AuthorizationToken{} }
func (m *AuthorizationToken) String() string { return proto.CompactTextString(m) }
func (*AuthorizationToken) ProtoMessage()    {}
func (*AuthorizationToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{6}
}

func (m *AuthorizationToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationToken.Unmarshal(m, b)
}
func (m *AuthorizationToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationToken.Marshal(b, m, deterministic)
}
func (m *AuthorizationToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationToken.Merge(m, src)
}
func (m *AuthorizationToken) XXX_Size() int {
	return xxx_messageInfo_AuthorizationToken.Size(m)
}
func (m *AuthorizationToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationToken.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationToken proto.InternalMessageInfo

func (m *AuthorizationToken) GetAuthorizationToken() string {
	if m != nil {
		return m.AuthorizationToken
	}
	return ""
}

// An access token.
type AccessToken struct {
	// The access token issued by the server.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// The new refresh token for obtaining access token later.
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Type of the token.
	TokenType AccessToken_TokenType `protobuf:"varint,3,opt,name=token_type,json=tokenType,proto3,enum=authcore.authapi.v1.AccessToken_TokenType" json:"token_type,omitempty"`
	// The lifetime in seconds of the access token.
	ExpiresIn int64 `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	// The ID token issued by the server.
	IdToken              string   `protobuf:"bytes,5,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{7}
}

func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (m *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(m, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

func (m *AccessToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AccessToken) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *AccessToken) GetTokenType() AccessToken_TokenType {
	if m != nil {
		return m.TokenType
	}
	return AccessToken_BEARER
}

func (m *AccessToken) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *AccessToken) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

// A password verifier of a given username-password pair for the server to authenticate the user
// via the SPAKE2+ protocol.
type PasswordVerifier struct {
	// The salt used to hash the password.
	Salt []byte `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	// The password verifier defined by the SPAKE2+ protocol.
	VerifierW0 []byte `protobuf:"bytes,2,opt,name=verifierW0,proto3" json:"verifierW0,omitempty"`
	// The password verifier defined by the SPAKE2+ protocol.
	VerifierL            []byte   `protobuf:"bytes,3,opt,name=verifierL,proto3" json:"verifierL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordVerifier) Reset()         { *m = PasswordVerifier{} }
func (m *PasswordVerifier) String() string { return proto.CompactTextString(m) }
func (*PasswordVerifier) ProtoMessage()    {}
func (*PasswordVerifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{8}
}

func (m *PasswordVerifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordVerifier.Unmarshal(m, b)
}
func (m *PasswordVerifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordVerifier.Marshal(b, m, deterministic)
}
func (m *PasswordVerifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordVerifier.Merge(m, src)
}
func (m *PasswordVerifier) XXX_Size() int {
	return xxx_messageInfo_PasswordVerifier.Size(m)
}
func (m *PasswordVerifier) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordVerifier.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordVerifier proto.InternalMessageInfo

func (m *PasswordVerifier) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *PasswordVerifier) GetVerifierW0() []byte {
	if m != nil {
		return m.VerifierW0
	}
	return nil
}

func (m *PasswordVerifier) GetVerifierL() []byte {
	if m != nil {
		return m.VerifierL
	}
	return nil
}

// The SPAKE2+ challenge from the server (incomingMessage from SPAKE2+).
type PasswordChallenge struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// The key-exchange response message of the server.
	Message              []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordChallenge) Reset()         { *m = PasswordChallenge{} }
func (m *PasswordChallenge) String() string { return proto.CompactTextString(m) }
func (*PasswordChallenge) ProtoMessage()    {}
func (*PasswordChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{9}
}

func (m *PasswordChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordChallenge.Unmarshal(m, b)
}
func (m *PasswordChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordChallenge.Marshal(b, m, deterministic)
}
func (m *PasswordChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordChallenge.Merge(m, src)
}
func (m *PasswordChallenge) XXX_Size() int {
	return xxx_messageInfo_PasswordChallenge.Size(m)
}
func (m *PasswordChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordChallenge proto.InternalMessageInfo

func (m *PasswordChallenge) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PasswordChallenge) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

// The SPAKE2+ response (comfirmation for SPAKE2+).
type PasswordResponse struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// The confirmation message of the client.
	Confirmation         []byte   `protobuf:"bytes,2,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordResponse) Reset()         { *m = PasswordResponse{} }
func (m *PasswordResponse) String() string { return proto.CompactTextString(m) }
func (*PasswordResponse) ProtoMessage()    {}
func (*PasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{10}
}

func (m *PasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordResponse.Unmarshal(m, b)
}
func (m *PasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordResponse.Marshal(b, m, deterministic)
}
func (m *PasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordResponse.Merge(m, src)
}
func (m *PasswordResponse) XXX_Size() int {
	return xxx_messageInfo_PasswordResponse.Size(m)
}
func (m *PasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordResponse proto.InternalMessageInfo

func (m *PasswordResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PasswordResponse) GetConfirmation() []byte {
	if m != nil {
		return m.Confirmation
	}
	return nil
}

// An OAuth response.
type OAuthResponse struct {
	Service              OAuthFactor_OAuthService `protobuf:"varint,1,opt,name=service,proto3,enum=authcore.authapi.v1.OAuthFactor_OAuthService" json:"service,omitempty"`
	Code                 string                   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OAuthResponse) Reset()         { *m = OAuthResponse{} }
func (m *OAuthResponse) String() string { return proto.CompactTextString(m) }
func (*OAuthResponse) ProtoMessage()    {}
func (*OAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{11}
}

func (m *OAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthResponse.Unmarshal(m, b)
}
func (m *OAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthResponse.Marshal(b, m, deterministic)
}
func (m *OAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthResponse.Merge(m, src)
}
func (m *OAuthResponse) XXX_Size() int {
	return xxx_messageInfo_OAuthResponse.Size(m)
}
func (m *OAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthResponse proto.InternalMessageInfo

func (m *OAuthResponse) GetService() OAuthFactor_OAuthService {
	if m != nil {
		return m.Service
	}
	return OAuthFactor_FACEBOOK
}

func (m *OAuthResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// An proof-of-work challenge.
type ProofOfWorkChallenge struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Challenge            string   `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Purpose              string   `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Difficulty           int64    `protobuf:"varint,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProofOfWorkChallenge) Reset()         { *m = ProofOfWorkChallenge{} }
func (m *ProofOfWorkChallenge) String() string { return proto.CompactTextString(m) }
func (*ProofOfWorkChallenge) ProtoMessage()    {}
func (*ProofOfWorkChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{12}
}

func (m *ProofOfWorkChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofOfWorkChallenge.Unmarshal(m, b)
}
func (m *ProofOfWorkChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofOfWorkChallenge.Marshal(b, m, deterministic)
}
func (m *ProofOfWorkChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofOfWorkChallenge.Merge(m, src)
}
func (m *ProofOfWorkChallenge) XXX_Size() int {
	return xxx_messageInfo_ProofOfWorkChallenge.Size(m)
}
func (m *ProofOfWorkChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofOfWorkChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_ProofOfWorkChallenge proto.InternalMessageInfo

func (m *ProofOfWorkChallenge) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ProofOfWorkChallenge) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *ProofOfWorkChallenge) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *ProofOfWorkChallenge) GetDifficulty() int64 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

// An proof-of-work response.
type ProofOfWorkResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Response             string   `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProofOfWorkResponse) Reset()         { *m = ProofOfWorkResponse{} }
func (m *ProofOfWorkResponse) String() string { return proto.CompactTextString(m) }
func (*ProofOfWorkResponse) ProtoMessage()    {}
func (*ProofOfWorkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{13}
}

func (m *ProofOfWorkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofOfWorkResponse.Unmarshal(m, b)
}
func (m *ProofOfWorkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofOfWorkResponse.Marshal(b, m, deterministic)
}
func (m *ProofOfWorkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofOfWorkResponse.Merge(m, src)
}
func (m *ProofOfWorkResponse) XXX_Size() int {
	return xxx_messageInfo_ProofOfWorkResponse.Size(m)
}
func (m *ProofOfWorkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofOfWorkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProofOfWorkResponse proto.InternalMessageInfo

func (m *ProofOfWorkResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ProofOfWorkResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

// Information for time-based one-time password second factor.
type TOTPInfo struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Identifier           string   `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TOTPInfo) Reset()         { *m = TOTPInfo{} }
func (m *TOTPInfo) String() string { return proto.CompactTextString(m) }
func (*TOTPInfo) ProtoMessage()    {}
func (*TOTPInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{14}
}

func (m *TOTPInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TOTPInfo.Unmarshal(m, b)
}
func (m *TOTPInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TOTPInfo.Marshal(b, m, deterministic)
}
func (m *TOTPInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TOTPInfo.Merge(m, src)
}
func (m *TOTPInfo) XXX_Size() int {
	return xxx_messageInfo_TOTPInfo.Size(m)
}
func (m *TOTPInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TOTPInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TOTPInfo proto.InternalMessageInfo

func (m *TOTPInfo) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *TOTPInfo) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

// Information for SMS second factor.
type SMSInfo struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSInfo) Reset()         { *m = SMSInfo{} }
func (m *SMSInfo) String() string { return proto.CompactTextString(m) }
func (*SMSInfo) ProtoMessage()    {}
func (*SMSInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{15}
}

func (m *SMSInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSInfo.Unmarshal(m, b)
}
func (m *SMSInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSInfo.Marshal(b, m, deterministic)
}
func (m *SMSInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSInfo.Merge(m, src)
}
func (m *SMSInfo) XXX_Size() int {
	return xxx_messageInfo_SMSInfo.Size(m)
}
func (m *SMSInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SMSInfo proto.InternalMessageInfo

func (m *SMSInfo) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

// Information for backup code.
type BackupCodeInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupCodeInfo) Reset()         { *m = BackupCodeInfo{} }
func (m *BackupCodeInfo) String() string { return proto.CompactTextString(m) }
func (*BackupCodeInfo) ProtoMessage()    {}
func (*BackupCodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{16}
}

func (m *BackupCodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupCodeInfo.Unmarshal(m, b)
}
func (m *BackupCodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupCodeInfo.Marshal(b, m, deterministic)
}
func (m *BackupCodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupCodeInfo.Merge(m, src)
}
func (m *BackupCodeInfo) XXX_Size() int {
	return xxx_messageInfo_BackupCodeInfo.Size(m)
}
func (m *BackupCodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupCodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BackupCodeInfo proto.InternalMessageInfo

// Contact token response.
type ContactToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactToken) Reset()         { *m = ContactToken{} }
func (m *ContactToken) String() string { return proto.CompactTextString(m) }
func (*ContactToken) ProtoMessage()    {}
func (*ContactToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{17}
}

func (m *ContactToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactToken.Unmarshal(m, b)
}
func (m *ContactToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactToken.Marshal(b, m, deterministic)
}
func (m *ContactToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactToken.Merge(m, src)
}
func (m *ContactToken) XXX_Size() int {
	return xxx_messageInfo_ContactToken.Size(m)
}
func (m *ContactToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactToken.DiscardUnknown(m)
}

var xxx_messageInfo_ContactToken proto.InternalMessageInfo

func (m *ContactToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// Device registration.
type DeviceRegistration struct {
	DeviceToken          string               `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeviceRegistration) Reset()         { *m = DeviceRegistration{} }
func (m *DeviceRegistration) String() string { return proto.CompactTextString(m) }
func (*DeviceRegistration) ProtoMessage()    {}
func (*DeviceRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{18}
}

func (m *DeviceRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceRegistration.Unmarshal(m, b)
}
func (m *DeviceRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceRegistration.Marshal(b, m, deterministic)
}
func (m *DeviceRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceRegistration.Merge(m, src)
}
func (m *DeviceRegistration) XXX_Size() int {
	return xxx_messageInfo_DeviceRegistration.Size(m)
}
func (m *DeviceRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceRegistration proto.InternalMessageInfo

func (m *DeviceRegistration) GetDeviceToken() string {
	if m != nil {
		return m.DeviceToken
	}
	return ""
}

func (m *DeviceRegistration) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

// An TOTP authenticator.
type TOTPAuthenticator struct {
	Id                   int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Identifier           string                   `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Status               TOTPAuthenticator_Status `protobuf:"varint,3,opt,name=status,proto3,enum=authcore.authapi.v1.TOTPAuthenticator_Status" json:"status,omitempty"`
	CreatedAt            *timestamp.Timestamp     `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt           *timestamp.Timestamp     `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *TOTPAuthenticator) Reset()         { *m = TOTPAuthenticator{} }
func (m *TOTPAuthenticator) String() string { return proto.CompactTextString(m) }
func (*TOTPAuthenticator) ProtoMessage()    {}
func (*TOTPAuthenticator) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{19}
}

func (m *TOTPAuthenticator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TOTPAuthenticator.Unmarshal(m, b)
}
func (m *TOTPAuthenticator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TOTPAuthenticator.Marshal(b, m, deterministic)
}
func (m *TOTPAuthenticator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TOTPAuthenticator.Merge(m, src)
}
func (m *TOTPAuthenticator) XXX_Size() int {
	return xxx_messageInfo_TOTPAuthenticator.Size(m)
}
func (m *TOTPAuthenticator) XXX_DiscardUnknown() {
	xxx_messageInfo_TOTPAuthenticator.DiscardUnknown(m)
}

var xxx_messageInfo_TOTPAuthenticator proto.InternalMessageInfo

func (m *TOTPAuthenticator) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TOTPAuthenticator) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *TOTPAuthenticator) GetStatus() TOTPAuthenticator_Status {
	if m != nil {
		return m.Status
	}
	return TOTPAuthenticator_ACTIVE
}

func (m *TOTPAuthenticator) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *TOTPAuthenticator) GetLastUsedAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastUsedAt
	}
	return nil
}

// An OAuth factor.
type OAuthFactor struct {
	Id                   int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64                    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Service              OAuthFactor_OAuthService `protobuf:"varint,3,opt,name=service,proto3,enum=authcore.authapi.v1.OAuthFactor_OAuthService" json:"service,omitempty"`
	OauthUserId          string                   `protobuf:"bytes,4,opt,name=oauth_user_id,json=oauthUserId,proto3" json:"oauth_user_id,omitempty"`
	Metadata             string                   `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt            *timestamp.Timestamp     `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt           *timestamp.Timestamp     `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OAuthFactor) Reset()         { *m = OAuthFactor{} }
func (m *OAuthFactor) String() string { return proto.CompactTextString(m) }
func (*OAuthFactor) ProtoMessage()    {}
func (*OAuthFactor) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{20}
}

func (m *OAuthFactor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthFactor.Unmarshal(m, b)
}
func (m *OAuthFactor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthFactor.Marshal(b, m, deterministic)
}
func (m *OAuthFactor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthFactor.Merge(m, src)
}
func (m *OAuthFactor) XXX_Size() int {
	return xxx_messageInfo_OAuthFactor.Size(m)
}
func (m *OAuthFactor) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthFactor.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthFactor proto.InternalMessageInfo

func (m *OAuthFactor) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OAuthFactor) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OAuthFactor) GetService() OAuthFactor_OAuthService {
	if m != nil {
		return m.Service
	}
	return OAuthFactor_FACEBOOK
}

func (m *OAuthFactor) GetOauthUserId() string {
	if m != nil {
		return m.OauthUserId
	}
	return ""
}

func (m *OAuthFactor) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *OAuthFactor) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *OAuthFactor) GetLastUsedAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastUsedAt
	}
	return nil
}

// An Second factor.
type SecondFactor struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type                 SecondFactor_Type     `protobuf:"varint,3,opt,name=type,proto3,enum=authcore.authapi.v1.SecondFactor_Type" json:"type,omitempty"`
	Content              *SecondFactor_Content `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt            *timestamp.Timestamp  `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt           *timestamp.Timestamp  `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SecondFactor) Reset()         { *m = SecondFactor{} }
func (m *SecondFactor) String() string { return proto.CompactTextString(m) }
func (*SecondFactor) ProtoMessage()    {}
func (*SecondFactor) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{21}
}

func (m *SecondFactor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecondFactor.Unmarshal(m, b)
}
func (m *SecondFactor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecondFactor.Marshal(b, m, deterministic)
}
func (m *SecondFactor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecondFactor.Merge(m, src)
}
func (m *SecondFactor) XXX_Size() int {
	return xxx_messageInfo_SecondFactor.Size(m)
}
func (m *SecondFactor) XXX_DiscardUnknown() {
	xxx_messageInfo_SecondFactor.DiscardUnknown(m)
}

var xxx_messageInfo_SecondFactor proto.InternalMessageInfo

func (m *SecondFactor) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SecondFactor) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SecondFactor) GetType() SecondFactor_Type {
	if m != nil {
		return m.Type
	}
	return SecondFactor_SMS
}

func (m *SecondFactor) GetContent() *SecondFactor_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *SecondFactor) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *SecondFactor) GetLastUsedAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastUsedAt
	}
	return nil
}

type SecondFactor_Content struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Identifier           string   `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Used                 int64    `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Codes                []string `protobuf:"bytes,4,rep,name=codes,proto3" json:"codes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecondFactor_Content) Reset()         { *m = SecondFactor_Content{} }
func (m *SecondFactor_Content) String() string { return proto.CompactTextString(m) }
func (*SecondFactor_Content) ProtoMessage()    {}
func (*SecondFactor_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{21, 0}
}

func (m *SecondFactor_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecondFactor_Content.Unmarshal(m, b)
}
func (m *SecondFactor_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecondFactor_Content.Marshal(b, m, deterministic)
}
func (m *SecondFactor_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecondFactor_Content.Merge(m, src)
}
func (m *SecondFactor_Content) XXX_Size() int {
	return xxx_messageInfo_SecondFactor_Content.Size(m)
}
func (m *SecondFactor_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_SecondFactor_Content.DiscardUnknown(m)
}

var xxx_messageInfo_SecondFactor_Content proto.InternalMessageInfo

func (m *SecondFactor_Content) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SecondFactor_Content) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *SecondFactor_Content) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *SecondFactor_Content) GetCodes() []string {
	if m != nil {
		return m.Codes
	}
	return nil
}

// An contact verification code.
type ContactVerificationCode struct {
	ContactId            string   `protobuf:"bytes,1,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactVerificationCode) Reset()         { *m = ContactVerificationCode{} }
func (m *ContactVerificationCode) String() string { return proto.CompactTextString(m) }
func (*ContactVerificationCode) ProtoMessage()    {}
func (*ContactVerificationCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0161b0683ac6e5, []int{22}
}

func (m *ContactVerificationCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactVerificationCode.Unmarshal(m, b)
}
func (m *ContactVerificationCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactVerificationCode.Marshal(b, m, deterministic)
}
func (m *ContactVerificationCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactVerificationCode.Merge(m, src)
}
func (m *ContactVerificationCode) XXX_Size() int {
	return xxx_messageInfo_ContactVerificationCode.Size(m)
}
func (m *ContactVerificationCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactVerificationCode.DiscardUnknown(m)
}

var xxx_messageInfo_ContactVerificationCode proto.InternalMessageInfo

func (m *ContactVerificationCode) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

func (m *ContactVerificationCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterEnum("authcore.authapi.v1.AuthenticationState_ChallengeType", AuthenticationState_ChallengeType_name, AuthenticationState_ChallengeType_value)
	proto.RegisterEnum("authcore.authapi.v1.ResetPasswordAuthenticationState_ChallengeType", ResetPasswordAuthenticationState_ChallengeType_name, ResetPasswordAuthenticationState_ChallengeType_value)
	proto.RegisterEnum("authcore.authapi.v1.Contact_Type", Contact_Type_name, Contact_Type_value)
	proto.RegisterEnum("authcore.authapi.v1.AuditLogEntity_Result", AuditLogEntity_Result_name, AuditLogEntity_Result_value)
	proto.RegisterEnum("authcore.authapi.v1.AccessToken_TokenType", AccessToken_TokenType_name, AccessToken_TokenType_value)
	proto.RegisterEnum("authcore.authapi.v1.TOTPAuthenticator_Status", TOTPAuthenticator_Status_name, TOTPAuthenticator_Status_value)
	proto.RegisterEnum("authcore.authapi.v1.OAuthFactor_OAuthService", OAuthFactor_OAuthService_name, OAuthFactor_OAuthService_value)
	proto.RegisterEnum("authcore.authapi.v1.SecondFactor_Type", SecondFactor_Type_name, SecondFactor_Type_value)
	proto.RegisterType((*AuthenticationState)(nil), "authcore.authapi.v1.AuthenticationState")
	proto.RegisterType((*ResetPasswordAuthenticationState)(nil), "authcore.authapi.v1.ResetPasswordAuthenticationState")
	proto.RegisterType((*User)(nil), "authcore.authapi.v1.User")
	proto.RegisterType((*Contact)(nil), "authcore.authapi.v1.Contact")
	proto.RegisterType((*Session)(nil), "authcore.authapi.v1.Session")
	proto.RegisterType((*AuditLogEntity)(nil), "authcore.authapi.v1.AuditLogEntity")
	proto.RegisterType((*AuthorizationToken)(nil), "authcore.authapi.v1.AuthorizationToken")
	proto.RegisterType((*AccessToken)(nil), "authcore.authapi.v1.AccessToken")
	proto.RegisterType((*PasswordVerifier)(nil), "authcore.authapi.v1.PasswordVerifier")
	proto.RegisterType((*PasswordChallenge)(nil), "authcore.authapi.v1.PasswordChallenge")
	proto.RegisterType((*PasswordResponse)(nil), "authcore.authapi.v1.PasswordResponse")
	proto.RegisterType((*OAuthResponse)(nil), "authcore.authapi.v1.OAuthResponse")
	proto.RegisterType((*ProofOfWorkChallenge)(nil), "authcore.authapi.v1.ProofOfWorkChallenge")
	proto.RegisterType((*ProofOfWorkResponse)(nil), "authcore.authapi.v1.ProofOfWorkResponse")
	proto.RegisterType((*TOTPInfo)(nil), "authcore.authapi.v1.TOTPInfo")
	proto.RegisterType((*SMSInfo)(nil), "authcore.authapi.v1.SMSInfo")
	proto.RegisterType((*BackupCodeInfo)(nil), "authcore.authapi.v1.BackupCodeInfo")
	proto.RegisterType((*ContactToken)(nil), "authcore.authapi.v1.ContactToken")
	proto.RegisterType((*DeviceRegistration)(nil), "authcore.authapi.v1.DeviceRegistration")
	proto.RegisterType((*TOTPAuthenticator)(nil), "authcore.authapi.v1.TOTPAuthenticator")
	proto.RegisterType((*OAuthFactor)(nil), "authcore.authapi.v1.OAuthFactor")
	proto.RegisterType((*SecondFactor)(nil), "authcore.authapi.v1.SecondFactor")
	proto.RegisterType((*SecondFactor_Content)(nil), "authcore.authapi.v1.SecondFactor.Content")
	proto.RegisterType((*ContactVerificationCode)(nil), "authcore.authapi.v1.ContactVerificationCode")
}

func init() { proto.RegisterFile("authapi/authcore_entity.proto", fileDescriptor_6b0161b0683ac6e5) }

var fileDescriptor_6b0161b0683ac6e5 = []byte{
	// 2011 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0x5b, 0x6f, 0xdb, 0xc8,
	0x15, 0xb6, 0x2e, 0xd6, 0xe5, 0xe8, 0x12, 0x7a, 0xe2, 0xd8, 0x5a, 0xaf, 0xd3, 0x55, 0xb8, 0xe9,
	0xd6, 0xbb, 0xc8, 0xca, 0x5b, 0x2f, 0x7a, 0x45, 0x5f, 0x68, 0x85, 0xc9, 0x0a, 0xb1, 0x25, 0x81,
	0x94, 0x63, 0xa0, 0x2f, 0x04, 0x43, 0x8e, 0x14, 0x22, 0x12, 0x49, 0xcc, 0x0c, 0xdd, 0x75, 0x9f,
	0x5b, 0xf4, 0xb9, 0xe8, 0x8f, 0xe8, 0x7f, 0x28, 0xfa, 0x37, 0xda, 0xf7, 0xfe, 0x86, 0xfe, 0x81,
	0x62, 0x2e, 0xa4, 0x28, 0x59, 0x89, 0x62, 0x2c, 0xd0, 0x7d, 0xb1, 0x79, 0x0e, 0xcf, 0x39, 0x73,
	0xae, 0xdf, 0x1c, 0x0a, 0x1e, 0xbb, 0x09, 0x7b, 0xeb, 0xc6, 0xc1, 0x29, 0xff, 0xef, 0x45, 0x04,
	0x3b, 0x38, 0x64, 0x01, 0xbb, 0xed, 0xc5, 0x24, 0x62, 0x11, 0x7a, 0x98, 0xb2, 0x7b, 0x4a, 0xae,
	0x77, 0xf3, 0xf3, 0xa3, 0xcf, 0x66, 0x51, 0x34, 0x9b, 0xe3, 0x53, 0x21, 0xf2, 0x26, 0x99, 0x9e,
	0xb2, 0x60, 0x81, 0x29, 0x73, 0x17, 0xb1, 0xd4, 0x3a, 0xfa, 0x64, 0x5d, 0xc0, 0x0d, 0x95, 0xc1,
	0xa3, 0xe3, 0xf5, 0x57, 0x94, 0x91, 0xc4, 0x63, 0xf2, 0xad, 0xfe, 0xef, 0x32, 0x3c, 0x34, 0x12,
	0xf6, 0x96, 0xfb, 0xe0, 0xb9, 0x2c, 0x88, 0x42, 0x9b, 0xb9, 0x0c, 0xa3, 0x9f, 0xc1, 0x03, 0x86,
	0x17, 0x71, 0x44, 0x5c, 0x72, 0xeb, 0xb0, 0xe8, 0x1d, 0x0e, 0x3b, 0x85, 0x6e, 0xe1, 0xa4, 0x6e,
	0xb5, 0x33, 0xf6, 0x84, 0x73, 0xd1, 0x53, 0x68, 0xb9, 0x4b, 0x7d, 0xec, 0x77, 0x8a, 0xdd, 0xc2,
	0x49, 0xcd, 0x5a, 0x65, 0xa2, 0x33, 0x78, 0xb4, 0xc2, 0x70, 0x12, 0x8a, 0x89, 0x13, 0xf8, 0x9d,
	0x92, 0x30, 0xfa, 0x70, 0xe5, 0xe5, 0x15, 0xc5, 0x64, 0xe0, 0xa3, 0xd7, 0x00, 0xde, 0x5b, 0x77,
	0x3e, 0xc7, 0xe1, 0x0c, 0xd3, 0x4e, 0xb9, 0x5b, 0x3a, 0x69, 0x9f, 0xfd, 0xb2, 0xb7, 0x21, 0x3d,
	0xbd, 0x0d, 0x01, 0xf4, 0xfa, 0xa9, 0xea, 0xe4, 0x36, 0xc6, 0x56, 0xce, 0x12, 0xba, 0x02, 0x14,
	0xbb, 0x94, 0xfe, 0x21, 0x22, 0xbe, 0x93, 0xb1, 0x3b, 0xbb, 0xdd, 0xc2, 0x49, 0xe3, 0xec, 0x8b,
	0x8d, 0xf6, 0xc7, 0x4a, 0x3c, 0xb3, 0x69, 0xed, 0xc5, 0xeb, 0x2c, 0xf4, 0x39, 0xb4, 0x32, 0xb3,
	0xd4, 0x9d, 0xb3, 0x4e, 0xb5, 0x5b, 0x38, 0x69, 0x5a, 0xcd, 0x94, 0x69, 0xbb, 0x73, 0x86, 0x4e,
	0x41, 0x84, 0x1a, 0x91, 0xe0, 0x8f, 0xc2, 0x57, 0x95, 0xda, 0x8a, 0xc8, 0x02, 0x5a, 0x79, 0x25,
	0xd3, 0xfb, 0x04, 0x9a, 0x04, 0xfb, 0x01, 0xc1, 0x1e, 0x73, 0x12, 0x32, 0xef, 0xd4, 0x84, 0x64,
	0x23, 0xe5, 0x5d, 0x91, 0xb9, 0xfe, 0xb7, 0x02, 0xb4, 0x56, 0xa2, 0x45, 0x4d, 0xa8, 0x8d, 0x0d,
	0xdb, 0xbe, 0x1e, 0x59, 0xcf, 0xb5, 0x1d, 0xd4, 0x85, 0xe3, 0xc9, 0xe0, 0xd2, 0x74, 0xce, 0x0d,
	0xdb, 0x7c, 0xee, 0x8c, 0x86, 0xa6, 0x23, 0xc8, 0x4c, 0xa2, 0x80, 0x3a, 0xb0, 0x7f, 0x35, 0x1c,
	0xbc, 0x36, 0x2d, 0xdb, 0xb8, 0x70, 0x26, 0xd7, 0x23, 0xe7, 0x85, 0xd1, 0x9f, 0x8c, 0x2c, 0xad,
	0x88, 0xda, 0x00, 0xe6, 0xa5, 0x31, 0xb8, 0x70, 0xfa, 0xa3, 0xe7, 0xa6, 0x56, 0xe2, 0x96, 0xed,
	0x4b, 0x5b, 0x52, 0x65, 0x54, 0x87, 0xdd, 0x91, 0x71, 0x35, 0xf9, 0x4e, 0xdb, 0x45, 0x0f, 0xa0,
	0x71, 0x6e, 0xf4, 0x5f, 0x5d, 0x8d, 0xe5, 0xbb, 0x8a, 0xfe, 0x9f, 0x22, 0x74, 0x2d, 0x4c, 0x31,
	0x4b, 0x93, 0xf7, 0x7f, 0xe8, 0xb2, 0x6f, 0xe1, 0x80, 0xf0, 0x23, 0x9d, 0xac, 0x10, 0x6b, 0x6d,
	0x46, 0xf2, 0x0e, 0xa9, 0x36, 0xf3, 0x36, 0xb4, 0x59, 0x7f, 0x63, 0x1b, 0x6c, 0x0b, 0xe7, 0x03,
	0x3d, 0xf7, 0x0d, 0xec, 0xaf, 0x79, 0x26, 0xa3, 0xdd, 0x95, 0x85, 0x5f, 0xf1, 0x4b, 0x44, 0xac,
	0xeb, 0xeb, 0x45, 0xdd, 0x83, 0x56, 0x7f, 0x34, 0x9c, 0x18, 0xfd, 0x89, 0x33, 0x19, 0xbd, 0x32,
	0x87, 0xda, 0x8e, 0xfe, 0xe7, 0x1a, 0x94, 0x79, 0x14, 0xa8, 0x0d, 0xc5, 0xc0, 0x57, 0xa9, 0x2b,
	0x06, 0x3e, 0x3a, 0x82, 0x1a, 0x8f, 0x3c, 0x74, 0x17, 0x58, 0x64, 0xaa, 0x6e, 0x65, 0xb4, 0xe8,
	0x53, 0x12, 0x2c, 0x78, 0xc6, 0xf1, 0xc2, 0x0d, 0xe6, 0x2a, 0x37, 0x4d, 0xc5, 0x34, 0x39, 0x0f,
	0x8d, 0xe1, 0x60, 0x45, 0xc8, 0xb9, 0xc1, 0x24, 0x98, 0x06, 0xd8, 0xef, 0xb4, 0xc5, 0x9c, 0x1c,
	0xf5, 0x24, 0xaa, 0xf4, 0x52, 0x54, 0xe9, 0x4d, 0x52, 0x44, 0xb2, 0xf6, 0xf3, 0x96, 0x5e, 0x2b,
	0xbd, 0xfc, 0xb1, 0xf1, 0xdb, 0x28, 0xc4, 0x9d, 0xf2, 0xca, 0xb1, 0x63, 0xce, 0xcb, 0x1f, 0x2b,
	0x84, 0x96, 0xc7, 0x3e, 0xf8, 0xe8, 0x63, 0x85, 0xa5, 0xec, 0xd8, 0x9f, 0x42, 0x9b, 0x60, 0x2f,
	0xba, 0xc1, 0x59, 0xb8, 0x48, 0x9c, 0xdb, 0x4a, 0xb9, 0x32, 0x5e, 0x0b, 0x0e, 0x57, 0xc5, 0x96,
	0x27, 0x3f, 0xdc, 0x7a, 0xf2, 0xa3, 0x15, 0x5b, 0xd9, 0xd1, 0x4f, 0xa0, 0xe9, 0x07, 0x34, 0x9e,
	0xbb, 0xb7, 0x8e, 0x28, 0x84, 0xac, 0x75, 0x43, 0xf1, 0x86, 0xbc, 0x16, 0x9f, 0x42, 0x5d, 0x76,
	0x68, 0x38, 0x8d, 0x14, 0x08, 0x88, 0x42, 0x0d, 0xc2, 0x69, 0x84, 0x7e, 0x07, 0xcd, 0xb9, 0x4b,
	0x99, 0x43, 0x31, 0x0e, 0x1d, 0x97, 0x75, 0xf6, 0xb7, 0x3a, 0x02, 0x5c, 0xde, 0xc6, 0x38, 0x34,
	0x18, 0xfa, 0x0d, 0x40, 0x12, 0xfb, 0x02, 0x6b, 0x5d, 0x89, 0x45, 0x1f, 0xd6, 0xad, 0x2b, 0x69,
	0xa9, 0xea, 0x11, 0x9c, 0xaa, 0xd6, 0xb6, 0xab, 0x2a, 0x69, 0x83, 0xa1, 0x5f, 0x43, 0xcd, 0x8b,
	0x42, 0xe6, 0x7a, 0x8c, 0x76, 0xea, 0xdd, 0xd2, 0x49, 0xe3, 0xec, 0x78, 0xe3, 0x28, 0xf5, 0xa5,
	0x90, 0x95, 0x49, 0xa3, 0xaf, 0x01, 0xd1, 0x05, 0x75, 0xdc, 0x95, 0xb1, 0xea, 0x80, 0x18, 0xf3,
	0x3d, 0xba, 0xa0, 0xab, 0xf3, 0x86, 0x0e, 0xa0, 0x32, 0x8f, 0xbc, 0x77, 0xd8, 0xef, 0x34, 0x84,
	0x88, 0xa2, 0xd0, 0x39, 0x3c, 0xe0, 0x4f, 0x0e, 0xfe, 0x3e, 0x0e, 0x88, 0x0c, 0xa0, 0xb9, 0x35,
	0x80, 0x16, 0x57, 0x31, 0xa5, 0x86, 0xc1, 0xd0, 0x97, 0xa0, 0x09, 0x1b, 0x3e, 0xa6, 0x1e, 0x09,
	0x62, 0xe1, 0x48, 0x4b, 0x14, 0x47, 0xd8, 0x7e, 0xbe, 0x64, 0x73, 0x3c, 0x67, 0x11, 0x8b, 0xd7,
	0xdd, 0xd6, 0x84, 0x4f, 0x88, 0xbf, 0x5a, 0xf3, 0xfb, 0x57, 0x70, 0x98, 0x41, 0xc0, 0x9a, 0xd2,
	0x9e, 0x50, 0x3a, 0x88, 0x37, 0x02, 0x0c, 0x1f, 0xe9, 0xb9, 0x1b, 0xce, 0x12, 0x77, 0x86, 0x3b,
	0x8f, 0x64, 0xa7, 0xa4, 0xb4, 0xfe, 0x8f, 0x02, 0x54, 0x55, 0x46, 0x73, 0x50, 0x50, 0x12, 0x50,
	0xf0, 0x0b, 0x28, 0xb3, 0xdb, 0x58, 0xc2, 0x40, 0xfb, 0xec, 0xc9, 0x87, 0xaa, 0xd1, 0x13, 0xb0,
	0x25, 0xc4, 0xd1, 0x3e, 0xec, 0xde, 0xb8, 0xf3, 0x04, 0x2b, 0x74, 0x90, 0x04, 0x77, 0x22, 0x9b,
	0x8b, 0xb2, 0x70, 0x37, 0xa3, 0x51, 0x07, 0xaa, 0x6a, 0x02, 0x45, 0xa7, 0xd7, 0xac, 0x94, 0xd4,
	0x8f, 0xa1, 0x2c, 0x10, 0xac, 0x0e, 0xbb, 0xe2, 0x32, 0xd1, 0x76, 0xf8, 0xe3, 0xf8, 0xbb, 0xd1,
	0xd0, 0xd4, 0x0a, 0xfa, 0x5f, 0x4b, 0x50, 0xb5, 0x31, 0xa5, 0x3c, 0xc8, 0x75, 0x1c, 0x3b, 0x84,
	0x6a, 0x8a, 0xe0, 0x12, 0xc6, 0x2a, 0x89, 0x04, 0xed, 0x4f, 0xa1, 0xee, 0xe3, 0x9b, 0xc0, 0xc3,
	0x4b, 0x70, 0xaf, 0x49, 0xc6, 0xc0, 0x47, 0xdd, 0xfc, 0xe0, 0x04, 0xb1, 0x42, 0x9a, 0x6c, 0x38,
	0x06, 0xf1, 0x9d, 0xd1, 0xda, 0xbd, 0xd7, 0x68, 0x3d, 0x03, 0xb4, 0xd4, 0x9e, 0x47, 0xaa, 0x7c,
	0x72, 0x7c, 0xb5, 0x54, 0xee, 0x42, 0xf1, 0xd1, 0x63, 0x00, 0x11, 0x83, 0x3b, 0xc3, 0xa1, 0x1c,
	0xc4, 0xba, 0x25, 0xa6, 0xde, 0xe0, 0x0c, 0x3e, 0x6c, 0xb9, 0x5e, 0xfd, 0x88, 0x61, 0xc3, 0x59,
	0x9f, 0xae, 0xce, 0x69, 0xfd, 0x3e, 0x73, 0xfa, 0x18, 0x20, 0xa0, 0x8e, 0x97, 0x10, 0xc2, 0x9d,
	0x92, 0x53, 0x56, 0x0f, 0x68, 0x5f, 0x32, 0xf4, 0x7f, 0x96, 0xa0, 0x6d, 0x24, 0x7e, 0xc0, 0x2e,
	0xa2, 0x99, 0x29, 0xb6, 0xd3, 0x7b, 0x5d, 0x31, 0x07, 0x50, 0x71, 0x3d, 0x91, 0x14, 0x59, 0x1a,
	0x45, 0xa1, 0x53, 0xa8, 0x30, 0x97, 0xcc, 0x30, 0x13, 0x25, 0x69, 0x9c, 0x1d, 0xde, 0x71, 0xd6,
	0x16, 0xbb, 0xa9, 0xa5, 0xc4, 0xb8, 0x9b, 0x54, 0xb6, 0x06, 0xaf, 0xb3, 0x04, 0xd0, 0xba, 0xe2,
	0x0c, 0x7c, 0x7e, 0x8e, 0x2c, 0xba, 0x4a, 0xbe, 0xa2, 0x84, 0xaf, 0xb1, 0x4a, 0x75, 0x31, 0x88,
	0x51, 0x17, 0x1a, 0xf9, 0x59, 0x56, 0x3b, 0x54, 0x8e, 0x85, 0xce, 0xa1, 0x42, 0x30, 0x4d, 0xe6,
	0x32, 0x8d, 0xed, 0xb3, 0xaf, 0xde, 0xb3, 0x67, 0xe6, 0x53, 0xc2, 0xf7, 0x81, 0x64, 0xce, 0x2c,
	0xa5, 0x89, 0x3e, 0x83, 0x46, 0x40, 0x1d, 0xfc, 0x3d, 0xe3, 0x59, 0x98, 0xab, 0xa4, 0x42, 0x40,
	0x4d, 0xc5, 0x59, 0xab, 0x57, 0xe3, 0x1e, 0xf5, 0xd2, 0x9f, 0x41, 0x45, 0x9e, 0x86, 0x1a, 0x50,
	0xbd, 0x1a, 0xbe, 0x1a, 0x8e, 0xae, 0x87, 0xda, 0x0e, 0xaa, 0x41, 0xf9, 0x05, 0x1f, 0xa8, 0x02,
	0x67, 0xdb, 0x57, 0xfd, 0xbe, 0x69, 0xdb, 0x5a, 0x51, 0x37, 0x01, 0x19, 0x77, 0x57, 0xc9, 0xf7,
	0xec, 0x9e, 0x85, 0xf7, 0xed, 0x9e, 0xfa, 0x7f, 0x0b, 0xd0, 0x30, 0x3c, 0x0f, 0x53, 0x9a, 0xed,
	0xa2, 0xae, 0x20, 0x57, 0x34, 0x1b, 0x6e, 0x4e, 0xe4, 0x73, 0x68, 0x11, 0x3c, 0x25, 0x98, 0xbe,
	0x55, 0x32, 0xb2, 0x35, 0x9a, 0x8a, 0x29, 0x85, 0x06, 0x00, 0xe2, 0xa5, 0x23, 0x80, 0xa9, 0xf4,
	0xa1, 0x84, 0x2f, 0x4d, 0xf7, 0xc4, 0x5f, 0x81, 0x50, 0x75, 0x96, 0x3e, 0xf2, 0x06, 0x91, 0xf3,
	0x40, 0x9d, 0x20, 0x14, 0x5d, 0x55, 0x4a, 0x27, 0x84, 0x0e, 0x42, 0xf4, 0x09, 0xd4, 0x82, 0xd5,
	0x55, 0xab, 0x1a, 0xa8, 0xfd, 0xea, 0x10, 0xea, 0x99, 0x45, 0x04, 0x50, 0x39, 0x37, 0x0d, 0xcb,
	0xb4, 0xb4, 0x1d, 0xdd, 0x07, 0x2d, 0xdd, 0xc4, 0xd4, 0x55, 0x4e, 0x10, 0x82, 0xb2, 0x58, 0xe9,
	0x0b, 0x62, 0xa5, 0x17, 0xcf, 0xe8, 0x27, 0x00, 0x0a, 0xfb, 0xc8, 0xf5, 0x37, 0x22, 0xce, 0xa6,
	0x95, 0xe3, 0xa0, 0x63, 0xa8, 0xa7, 0xd4, 0x85, 0x08, 0xb2, 0x69, 0x2d, 0x19, 0x7a, 0x1f, 0xf6,
	0xee, 0x7c, 0x55, 0x70, 0xd0, 0xcd, 0x67, 0x56, 0x12, 0x1c, 0x58, 0x17, 0x98, 0x52, 0x0e, 0xfc,
	0xf2, 0x94, 0x94, 0xd4, 0x2f, 0x96, 0xae, 0x5a, 0x98, 0xc6, 0x51, 0x48, 0xdf, 0x67, 0x43, 0x87,
	0xa6, 0x17, 0x85, 0xd3, 0x80, 0x2c, 0x24, 0x58, 0x49, 0x43, 0x2b, 0x3c, 0x7d, 0x0e, 0xad, 0x11,
	0x6f, 0x9b, 0xcc, 0xd4, 0x4b, 0xa8, 0x52, 0x4c, 0xc4, 0x7c, 0x15, 0x44, 0x91, 0xbe, 0xde, 0x58,
	0x24, 0xa1, 0xf4, 0xc2, 0xf5, 0x58, 0x44, 0xe4, 0xb3, 0x2d, 0x95, 0xac, 0x54, 0x9b, 0xa7, 0xcf,
	0x8b, 0xfc, 0x14, 0x27, 0xc4, 0xb3, 0xfe, 0xa7, 0x02, 0xec, 0x8f, 0x49, 0x14, 0x4d, 0x47, 0xd3,
	0xeb, 0x88, 0xbc, 0xdb, 0x96, 0x84, 0x63, 0xa8, 0x2f, 0xbf, 0xd5, 0xa4, 0x9d, 0x25, 0x43, 0xdc,
	0x3d, 0x09, 0x89, 0x23, 0x9a, 0xde, 0x57, 0x29, 0xc9, 0xab, 0xe4, 0x07, 0xd3, 0x69, 0xe0, 0x25,
	0x73, 0x76, 0xab, 0x1a, 0x24, 0xc7, 0xd1, 0x5f, 0xc2, 0xc3, 0x9c, 0x17, 0x5b, 0xb2, 0x78, 0x04,
	0x35, 0xa2, 0x24, 0x52, 0xcc, 0x4b, 0x69, 0xfd, 0x1c, 0x6a, 0x93, 0xd1, 0x64, 0x2c, 0x36, 0xb7,
	0x03, 0xa8, 0x50, 0xec, 0x11, 0xcc, 0x94, 0xba, 0xa2, 0xb8, 0x33, 0x81, 0xcf, 0xef, 0x74, 0xde,
	0x03, 0xca, 0x42, 0x8e, 0xa3, 0x3f, 0x83, 0xaa, 0x7d, 0x69, 0x0b, 0x13, 0x4f, 0xa0, 0x29, 0x37,
	0xe0, 0x30, 0x59, 0xbc, 0xc1, 0x24, 0x9d, 0x35, 0xc1, 0x1b, 0x0a, 0x96, 0xae, 0x41, 0xfb, 0xdc,
	0xf5, 0xde, 0x25, 0x71, 0x3f, 0xf2, 0x31, 0x57, 0xd2, 0x9f, 0x42, 0x53, 0x5d, 0xe5, 0x72, 0xd0,
	0x36, 0x46, 0xa1, 0x13, 0x40, 0xcf, 0x05, 0x4e, 0x5a, 0x78, 0x16, 0x50, 0x46, 0xe4, 0x35, 0xc5,
	0xb7, 0x55, 0x79, 0xa3, 0xae, 0x0c, 0xb7, 0xe4, 0x49, 0x73, 0xab, 0xf8, 0x55, 0xbc, 0x0f, 0x7e,
	0xfd, 0xbd, 0x08, 0x7b, 0x3c, 0x3d, 0xb9, 0xa5, 0x26, 0x22, 0x77, 0x76, 0x95, 0x2d, 0xf9, 0x41,
	0x26, 0x54, 0x28, 0x73, 0x59, 0x42, 0x15, 0x68, 0x6c, 0xee, 0xc7, 0x3b, 0xe7, 0xf4, 0x6c, 0xa1,
	0x64, 0x29, 0xe5, 0xb5, 0x38, 0xca, 0xf7, 0xb9, 0x37, 0xd3, 0xc5, 0x21, 0xa1, 0x52, 0xf9, 0x23,
	0x17, 0x87, 0x2b, 0x2a, 0xb2, 0xa0, 0x43, 0x45, 0xba, 0xc2, 0x01, 0xc7, 0xe8, 0x4f, 0x06, 0xaf,
	0x4d, 0x6d, 0x87, 0x7f, 0x53, 0x0f, 0x86, 0x8a, 0x2a, 0xe8, 0x7f, 0x29, 0x41, 0x23, 0x37, 0x51,
	0x77, 0x72, 0xb4, 0xb6, 0x12, 0x95, 0xb2, 0x95, 0x28, 0x37, 0xad, 0xa5, 0x1f, 0x34, 0xad, 0x3a,
	0xb4, 0x22, 0xae, 0x90, 0x7d, 0x3c, 0xcb, 0xfd, 0xa9, 0x21, 0x98, 0xea, 0xa3, 0xf9, 0x08, 0x6a,
	0x0b, 0xcc, 0x5c, 0xdf, 0x65, 0xae, 0xba, 0x67, 0x33, 0x7a, 0x2d, 0xbd, 0xbb, 0x3f, 0x24, 0xbd,
	0x95, 0x7b, 0xa5, 0xf7, 0x12, 0x9a, 0xf9, 0x88, 0x78, 0x62, 0x5f, 0x18, 0x7d, 0xf3, 0x7c, 0x34,
	0x7a, 0xa5, 0xed, 0xf0, 0x94, 0xbf, 0x1c, 0x8d, 0x5e, 0x5e, 0x98, 0x5a, 0x81, 0xaf, 0x9f, 0xc6,
	0x78, 0x7c, 0x61, 0x6a, 0x45, 0x7e, 0x71, 0x5e, 0x1a, 0x93, 0x89, 0x69, 0xd9, 0x5a, 0x89, 0x13,
	0x93, 0xeb, 0x01, 0xa7, 0xb4, 0xb2, 0xfe, 0xaf, 0x12, 0x34, 0x6d, 0xec, 0x45, 0xa1, 0x7f, 0xdf,
	0x52, 0xfc, 0x56, 0xed, 0xdc, 0xb2, 0x0e, 0x9b, 0x7f, 0x53, 0xca, 0x5b, 0xce, 0x2f, 0xde, 0x7d,
	0xa8, 0xf2, 0x6f, 0x22, 0xbe, 0x96, 0xc9, 0xce, 0xfc, 0x72, 0xbb, 0x7a, 0x5f, 0x2a, 0x58, 0xa9,
	0xe6, 0x8f, 0x56, 0x82, 0xa3, 0x1b, 0xf9, 0x21, 0xc2, 0x7d, 0xd8, 0x8e, 0x60, 0x5b, 0xe7, 0x1d,
	0x41, 0x99, 0xbb, 0x21, 0xf2, 0x58, 0xb2, 0xc4, 0x33, 0xc7, 0x34, 0x7e, 0x7f, 0xc8, 0x5f, 0x6a,
	0xea, 0x96, 0x24, 0xf4, 0xaf, 0xd4, 0x27, 0x46, 0x15, 0x4a, 0xf6, 0xa5, 0x2d, 0x37, 0x23, 0x8e,
	0x03, 0x5a, 0x61, 0xfd, 0x97, 0xa9, 0xa2, 0x7e, 0x01, 0x87, 0x0a, 0x25, 0xe5, 0xfd, 0x2e, 0xf7,
	0x74, 0x0e, 0xa2, 0x7c, 0x9d, 0x50, 0x1f, 0xa4, 0x4e, 0xb6, 0xec, 0xd6, 0x15, 0x67, 0xe0, 0x6f,
	0xba, 0xc7, 0xce, 0xbf, 0xf8, 0xfd, 0xd3, 0xac, 0x3e, 0x41, 0x94, 0xfd, 0xa8, 0x7b, 0x1a, 0xbf,
	0x9b, 0x9d, 0xa6, 0xbf, 0xf2, 0xba, 0x71, 0xf0, 0xa6, 0x22, 0x32, 0xf7, 0xed, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x79, 0x9b, 0xec, 0x04, 0xff, 0x15, 0x00, 0x00,
}
